### ISSUE TITLE
Not successfully start the heron-executor because of some system dependent error

### ISSUE THREAD

**Issue by zhangzhonglai** [twitter/heron#1010]
These days I'm trying to make heron running on cluster mode with yarn scheduler. After fixing several compiling error and platform dependent error. It can start successfully and without error in log. But It still has problem.

I track the log and see following: 
tmaster:
```
Jun 30, 2016 5:04:56 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask call
INFO: Preparing evaluator for running executor-id: 0
Jun 30, 2016 5:04:56 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask getExecutorCommand
INFO: Executor command line: [./heron-core/bin/heron-executor, 0, AckingTopology, AckingTopology8e27cd3f-b90e-4c18-a59e-32a6dd05da43, AckingTopology.defn, 1:exclaim1:2:1:word:4:1:word:3:0:exclaim1:1:0, 28x003.xd.com:2181,28x004.xd.com:2181,28x005.xd.com:2181, /heron, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 46231, 42304, 50666, ./heron-conf/heron_internals.yaml, exclaim1:1073741824,word:1073741824, "", jar, heron-examples.jar, /usr/java/jdk1.7.0_67-cloudera, 39990, ./heron-core/bin/heron-shell, 59070, yarn, yarn, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 34119]
// added by myself
Jun 30, 2016 5:04:56 PM com.twitter.heron.spi.utils.ShellUtils runASyncProcess
INFO: working dir: /data/9/yarn/nm/usercache/yarn/appcache/application_1466049056624_1522/container_e14_1466049056624_1522_01_000002/.
Jun 30, 2016 5:04:56 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask call
INFO: Started heron executor-id: 0
```
stmgr:
```
Jun 30, 2016 5:04:59 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask call
INFO: Preparing evaluator for running executor-id: 1
Jun 30, 2016 5:04:59 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask getExecutorCommand
INFO: Executor command line: [./heron-core/bin/heron-executor, 1, AckingTopology, AckingTopology8e27cd3f-b90e-4c18-a59e-32a6dd05da43, AckingTopology.defn, 1:exclaim1:2:1:word:4:1:word:3:0:exclaim1:1:0, 28x003.xd.com:2181,28x004.xd.com:2181,28x005.xd.com:2181, /heron, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 51927, 57274, 35327, ./heron-conf/heron_internals.yaml, exclaim1:1073741824,word:1073741824, "", jar, heron-examples.jar, /usr/java/jdk1.7.0_67-cloudera, 48137, ./heron-core/bin/heron-shell, 56799, yarn, yarn, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 54309]
// added by myself
Jun 30, 2016 5:04:59 PM com.twitter.heron.spi.utils.ShellUtils runASyncProcess
INFO: working dir: /data/11/yarn/nm/usercache/yarn/appcache/application_1466049056624_1522/container_e14_1466049056624_1522_01_000003/.
Jun 30, 2016 5:04:59 PM com.twitter.heron.scheduler.yarn.HeronExecutorTask call
INFO: Started heron executor-id: 1
```
This means that the program has already run the code
`final Process regularExecutor = ShellUtils.runASyncProcess(true, executorCmd, new File("."));`.
But there is no tmaster or stmgr process on these machines.
Then if I manual execute the command copied from log in the working directory, the topology will work fine.
So I think there is a dead lock in `pb.start()`. Maybe!

Env:
```
OS: Centos 6.5
Scheduler: yarn
Git Branch: master
YARN Version: 2.6.0+cdh5.6.1+1092
JAVA Version: 1.7.0_67
```

**Comment by kramasamy** [comment]
@ashvina - Can you please respond?

**Comment by ashvina** [comment]
@zhangzhonglai `pb` is an instance of `java.lang.ProcessBuilder`. It seems unlikely that this code is blocking. The log messages you shared are generated before heron executor is launched. Some heron log files are also present in NodeManager's local directory (for e.g. `<NM_LOCAL_DIR>/usercache/heron/appcache/application_1466548964728_0004/container_1466548964728_0004_01_000002/log-files`). Could you please check and share some of those logs.

**Comment by ashvina** [comment]
@zhangzhonglai It would be helpful if you can share some information about your YARN cluster. Thanks.

**Comment by ashvina** [comment]
@zhangzhonglai  BTW, I have put some information about running the YARN scheduler on this doc page: https://github.com/ashvina/heron/blob/yarnSchedulerDoc-947/website/content/docs/operators/deployment/schedulers/yarn.md.

**Comment by zhangzhonglai** [comment]
@ashvina Actually there is only the first container's log-files exist. Other log-files generated from tmaster and stmgr are not existing in the working dir.
[log-files.tar.gz](https://github.com/twitter/heron/files/342821/log-files.tar.gz)
The working directory list of the first container is following:
```
total 51396
-rw-r--r-- 1 yarn yarn     2226 Jul  1 12:34 AckingTopology.defn
-rw-r--r-- 1 yarn yarn       68 Jul  1 12:35 container_tokens
-rwx------ 1 yarn yarn      641 Jul  1 12:35 default_container_executor_session.sh
-rwx------ 1 yarn yarn      695 Jul  1 12:35 default_container_executor.sh
-rw-r--r-- 1 yarn yarn 50412533 Jul  1 12:35 global.jar
drwxr-xr-x 2 yarn yarn     4096 Jan  1  1970 heron-conf
drwxr-xr-x 4 yarn yarn       26 Jan  1  1970 heron-core
-rwxr-xr-x 1 yarn yarn  2187258 Jan  1  1970 heron-examples.jar
-rwx------ 1 yarn yarn     3683 Jul  1 12:35 launch_container.sh
drwxr-xr-x 2 yarn yarn       96 Jul  1 12:35 log-files
lrwxrwxrwx 1 yarn yarn      116 Jul  1 12:35 reef -> /data/9/yarn/nm/usercache/yarn/appcache/application_1466049056624_1614/filecache/10/reef-job-7516731119712048753.jar
-r-xr-xr-x 1 yarn yarn      272 Jan  1  1970 release.yaml
drwx--x--- 2 yarn yarn        6 Jul  1 12:35 tmp
```
And next other contains' working directory:
tmaster
```
total 2168
-rw-r--r-- 1 yarn yarn    2226 Jul  1 12:34 AckingTopology.defn
-rw-r--r-- 1 yarn yarn      97 Jul  1 12:35 container_tokens
-rwx------ 1 yarn yarn     641 Jul  1 12:35 default_container_executor_session.sh
-rwx------ 1 yarn yarn     695 Jul  1 12:35 default_container_executor.sh
drwxr-xr-x 2 yarn yarn    4096 Jan  1  1970 heron-conf
drwxr-xr-x 4 yarn yarn      26 Jan  1  1970 heron-core
-rwxr-xr-x 1 yarn yarn 2187258 Jan  1  1970 heron-examples.jar
-rwx------ 1 yarn yarn    4093 Jul  1 12:35 launch_container.sh
-rw-r--r-- 1 yarn yarn       6 Jul  1 12:35 PID.txt
drwxr-xr-x 2 yarn yarn      31 Jul  1 12:35 reef
-r-xr-xr-x 1 yarn yarn     272 Jan  1  1970 release.yaml
drwx--x--- 2 yarn yarn       6 Jul  1 12:35 tmp
```
stmgr
```
total 2168
-rw-r--r-- 1 yarn yarn    2226 Jul  1 12:34 AckingTopology.defn
-rw-r--r-- 1 yarn yarn      97 Jul  1 12:35 container_tokens
-rwx------ 1 yarn yarn     645 Jul  1 12:35 default_container_executor_session.sh
-rwx------ 1 yarn yarn     699 Jul  1 12:35 default_container_executor.sh
drwxr-xr-x 2 yarn yarn    4096 Jan  1  1970 heron-conf
drwxr-xr-x 4 yarn yarn      26 Jan  1  1970 heron-core
-rwxr-xr-x 1 yarn yarn 2187258 Jan  1  1970 heron-examples.jar
-rwx------ 1 yarn yarn    4093 Jul  1 12:35 launch_container.sh
-rw-r--r-- 1 yarn yarn       6 Jul  1 12:35 PID.txt
drwxr-xr-x 2 yarn yarn      31 Jul  1 12:35 reef
-r-xr-xr-x 1 yarn yarn     272 Jan  1  1970 release.yaml
drwx--x--- 2 yarn yarn       6 Jul  1 12:35 tmp
```
You can see there's no log-files in their working directory. But the pb is actually running. 
My yarn cluster's configuration is almost default of CDH. What kind yarn information do you want?

**Comment by zhangzhonglai** [comment]
@ashvina I redirect the output and error stream of ProcessBuilder to tmp file. There is a Permission denied error in the tmp file.

It's my fault. I'm using the user `yarn` to submit the heron topology which hasn't a home directory. This means the $HOME env point to /home. Then heron use the pex to execute the heron-executor command. It will generate the .pex into $HOME/.pex which is permission denied.

For now, there is no way to know what happened between `pb.start()` and `the heron-executor started`. This will make people confused if some system dependent error were occurred at that time.

Finally, Thank you for taking time to focus on my issue. I will change the title and close this issue.

**Comment by zhangzhonglai** [comment]
@ashvina I find that my `yarn` user has a home directory which point to `/var/lib/hadoop-yarn`. So the problem is: the pex get an incorrect $HOME env for `yarn` user.

**Comment by ashvina** [comment]
@zhangzhonglai Thanks for providing the details. This seems like failure to launch executor. The YARN scheduler is expected have retried launching the job and generated logs. I will take a look at that scenario again.

**Comment by mycFelix** [comment]
@zhangzhonglai hi, I encountered the same problem about `the pex get an incorrect $HOME env for yarn user` on Yarn mode. 
Have you found a way to solve it or a correct configuration to make it right?

**Comment by zhangzhonglai** [comment]
@mycFelix Hi, I think there is a bit of difference between my problem with yours. My problem maybe encountered before the point of yours. Following is the error:
```
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 322, in execute
  File ".bootstrap/_pex/pex.py", line 78, in _activate
  File ".bootstrap/_pex/environment.py", line 132, in activate
  File ".bootstrap/_pex/environment.py", line 176, in _activate
  File ".bootstrap/_pex/environment.py", line 121, in update_candidate_distributions
  File ".bootstrap/_pex/environment.py", line 107, in load_internal_cache
  File ".bootstrap/_pex/environment.py", line 95, in write_zipped_internal_cache
  File ".bootstrap/_pex/util.py", line 176, in cache_distribution
  File ".bootstrap/_pex/common.py", line 124, in safe_open
  File ".bootstrap/_pex/common.py", line 112, in safe_mkdir
  File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/.pex/install'
```
My problem occurred when the pex is installing. So the error message will not exist in heron_executor.stdout. Because the heron_executor command can't run and the `heron_executor.stdout` file is not exist in path.
In your case, your problem occurred after the pex installed. Can you find the `.pex` directory in the yarn working directory?
I guess this problem maybe a system-dependent issue or config-dependent issue with python or pex. But I have no time to deal with the problem. 
Sorry, I have no idea of the problem for now.

**Comment by mycFelix** [comment]
@zhangzhonglai - Hi, thank you for your reply and helpful detail informations. I will review my configuration again and do more tests.
