### ISSUE TITLE
heron-ui: missing some resources files.

### ISSUE THREAD

**Issue by atibon** [twitter/heron#1013]
After I start heron-ui, I found I can't open the web site because missing some resources files, such as http://localhost//static/icomoon/fonts/icomoon.ttf http://localhost/static/img/logo54x54.png, and some js files. 

Can anybody help me?
![c203d309-1855-4710-b70a-3fd5e911e796](https://cloud.githubusercontent.com/assets/3862770/16495088/7f28c55c-3f1e-11e6-8854-a6e9ba77a838.png)

**Comment by nlu90** [comment]
@atibon How do you build and installed the tracker and ui?

Can you try the following command 

```
bazel run --config=darwin -- scripts/packages:heron-tools-install.sh --user
```

then start the `heron-tracker` and `heron-ui` in the terminal? And see the results.

**Comment by nlu90** [comment]
@atibon any updates?

**Comment by atibon** [comment]
thx,  I fix it. This is a network problem.
