### ISSUE TITLE
in heron what means storm taskid?

### ISSUE THREAD

**Issue by daxwang** [twitter/heron#1031]
in storm tuple, I can get which task it come from, then according to this taskid, i can hash this tuple to diffrent thread, but in heron Tuple no longer supports getSourceTask, so what should i do?

**Comment by maosongfu** [comment]
We have considered whether to keep this interface a long time ago and decided not to support it. Can I know what the benefits are to "hash this tuple to different thread" basing on the taskid, instead of its value , i.e. tuple.hashCode()?

**Comment by kramasamy** [comment]
@daxwang - should we close this, if this is not an issue?
