### ISSUE TITLE
Make forums prominent in web pages

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#1043]

**Comment by kramasamy** [comment]
@lucperkins and @lewiskan - any suggestions on this welcome.

**Comment by billonahill** [comment]
Druid does a good job with this: http://druid.io/community/

We could add some similar things to the top of our community page and maybe also clarify how questions and troubleshooting should be over email and only bugs via github issues.

**Comment by kramasamy** [comment]
Fixed in #1168
