### ISSUE TITLE
heron-explorer issue tracking

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1045]
just open an issue here so that we can track issues of `heron-explorer`. Feel free to mute this one.

**Comment by objmagic** [comment]
customizable default value for ``tracker_url``

**Comment by kramasamy** [comment]
@objmagic - let us create one github issue for each. Each issue can be prefixed by [heron-explorer] so that you can distinguish. Otherwise it will be difficult to track.

**Comment by objmagic** [comment]
ok.
