### ISSUE TITLE
heron-instance: MAT can't parse dump file. 

### ISSUE THREAD

**Issue by atibon** [twitter/heron#1057]
I found one Heron instance is running very slowly. The capacity was 100%. 
So I executed ``jmap -dump:live,format=b,file=/tmp/merge.bin``. Then, I downloaded it to my own PC, Finally I open it with MAT (memory analytics tool). However, the following error message showed up.

```
An internal error occurred during: "Parsing heap dump from '/Users/nobita/Downloads/mat/merge.bin'".
java.lang.NullPointerException
```

I guess something is wrong with ``jmap``. I tried several times, but I got the same problem every time.

**Comment by kramasamy** [comment]
@objmagic - can you check what is the issue?

**Comment by caofangkun** [comment]
Hi @atibon 
this is not a heron issue.  
It's more likely [MAT's/Eclipse MAT's bug] (https://bugs.eclipse.org/bugs/show_bug.cgi?id=471757)
please check more detail log following of the ```NullPointerException```.

**Comment by atibon** [comment]
@caofangkun I've fixed it.
