### ISSUE TITLE
heron-ui: Metrics is wrong. How can I fix it?

### ISSUE THREAD

**Issue by atibon** [twitter/heron#1063]
```
Bolt Counters - MAPPER

Metrics	10 mins	1 hr	3 hrs	All Time
Emit Count (default)	0	116619730	116619730	116619730
Execute Count (default)	0	7506	7506	7506
Ack Count (default)	0	0	0	0
Fail Count (default)	0	0	0	0
```

I wanna run some tests to see performance info, but the metrics is not right. I checked the data in zookeeper, but found nothing about metrics data.

How can I get the right metrics info?

**Comment by maosongfu** [comment]
You may try with heron-tracker: http://twitter.github.io/heron/docs/operators/heron-tracker/
And here is the RESTful API: http://twitter.github.io/heron/docs/operators/heron-tracker-api/

But heron-tracker provides only filtered metrics: https://github.com/twitter/heron/blob/master/heron/config/src/yaml/conf/examples/metrics_sinks.yaml#L44

If you want to get more metrics, one simple way is to look at metrics.json.* under working directory.

**Comment by objmagic** [comment]
@atibon what do you mean by "not right"? Could you please tell us which particular part of metrics is incorrect in the table above?

**Comment by atibon** [comment]
@objmagic For example, Emit Count for 10 mins  is 0. 
And sometimes all of the metrics value is 0.

**Comment by atibon** [comment]
@maosongfu Thx. I will try.

**Comment by objmagic** [comment]
interesting. cc/ @cckellogg . Could you please have a look at this problem?

**Comment by atibon** [comment]
@objmagic Maybe network problem. BTW, Must I collect all of metrics.json.* under hundreds of sandbox directories if I wanner get the correct data?

**Comment by objmagic** [comment]
@atibon I don't think you need to. If there is really something wrong with the metrics you see on Heron UI, I'd say it's our mistake to have ``heron-ui`` display incorrect information, which means it is not necessary for you to dig into ``metrics.json.*`` if you think our ``heron-ui`` fails to present you correct information.

**Comment by vinit1209** [comment]
Hi @atibon,
I'm submitted, my topology to split words from the sentence and count the words. It submitted successfully but in Metrics Emit Count(default), Complete Latency (ms)(default), Ack Count (default) and in Spout Instance Counters Emit Count | Complete Latency (ms) | Ack Count all are coming 0 could anyone help me why this is happening.
