### ISSUE TITLE
RoundRobinPacking over allocate resources

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#1073]
Currently `RoundRobinPacking` executes the following steps:

1. creates a packing plan and computes resources required by each container
2. finds the biggest container, i.e. container with the largest resource requirement, say R
3. assigns the largest resource (R) to all the containers

It seems the last step is required by clusters where heterogenous containers cannot be allocated, for .e.g. `Aurora`. As a result this `RoundRobinPacking` is not leveraging `yarn scheduler`'s ability to allocate heterogeneous container. 

Ideally the packing algorithm should create a packing plan independent of the runtime cluster. Hence the max resource computation logic should be moved to the scheduler or util classes.

**Comment by billonahill** [comment]
I don't know if we need to move the packing plan classes into specific schedulers, but we should have a concept of which packing plans are and are not supported (or ideal) for a given scheduler.

**Comment by ashvina** [comment]
I did not mean to move packing plan classes to schedulers. Sorry for the confusion. I am suggesting that scheduler specific computation be outside packing algorithm. For e.g. method `RoundRobinPacking.getLargestContainerRam` should be in moved to `AuroraScheduler` and should be used in `createAuroraProperties`. 

I can submit a patch to clarify in detail.

**Comment by ashvina** [comment]
@billonahill I created a patch for this https://github.com/ashvina/heron/commit/59234cf9acc3acfc5f43d2d3e4d3d742457a0be7

**Comment by kramasamy** [comment]
thanks @ashvina for this - it is a good idea to keep packing algorithms and schedulers orthogonal.
