### ISSUE TITLE
Topology STATUS on UI

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1083]
Hi

Where can i find the current status of Topology on Heron UI?

Is there a way to change the status of Topology form Heron UI?

Thanks

**Comment by kramasamy** [comment]
@mycFelix - have you started the heron-tracker and heron-ui as indicated in the documentation?

**Comment by mycFelix** [comment]
@kramasamy - thank you for your reply. I've started heron-tracker and heron-ui and i can see the Logical plan and Physical plan of the topology. I'm wondering if there has a way to `check` or `change` the status of topology from Heron UI, such as `activated` or `deactivate`, at less `check`. It would be more convenient than executing some shell commands.

**Comment by kramasamy** [comment]
@mycFelix - this is a pending feature request. Here is the relevant issue #187

**Comment by mycFelix** [comment]
@kramasamy - looking forward that feature. Thank you and please close my issue.
