### ISSUE TITLE
CLI TODO: extract to heron-core

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1087]
@kramasamy I'd like to know what this TODO means:

https://github.com/twitter/heron/commit/5381a8bd4bc1224d61fddaacefbb582e5b4838a8#diff-152db4c3dac8ab994af6e65b57f97175R42

**Comment by objmagic** [comment]
this is blocking #581 and #1072

**Comment by kramasamy** [comment]
@objmagic - is this completed?

**Comment by objmagic** [comment]
completed. close now.
