### ISSUE TITLE
doImmediateAcks and data processing guarantee

### ISSUE THREAD

**Issue by mhajibaba** [twitter/heron#1104]
Why heron use `doImmediateAcks` and why `collector.ack` called by user in a bolt is different from `ack` method in spout?
How I ensure that my message is processed by last bolt?
Is there any need to implement acking in heron or it guarantees message processing?

**Comment by maosongfu** [comment]
`doImmediateAcks` is an internal implementation and could be changed in future.

For:
 why `collector.ack` called by user in a bolt is different from `ack` method in spout?
How I ensure that my message is processed by last bolt?
Is there any need to implement acking in heron or it guarantees message processing?

This doc could help: http://storm.apache.org/releases/current/Guaranteeing-message-processing.html

**Comment by maosongfu** [comment]
Close since it is not an issue. Better to ask in google group.

**Comment by mhajibaba** [comment]
@maosongfu  your link about _guarantees message processing_ work just on Storm not heron!!!

**Comment by kramasamy** [comment]
We provide the same guarantees as storm - at least once and at most once.

Cheers
/Karthik

**Comment by maosongfu** [comment]
@mhajibaba Sorry I think I haven't explained clearly. Heron has compatible-api with storm and provides same guarantees as storm, so concept is shared and you can use heron acking mechanism as storm's.
