### ISSUE TITLE
Create web documentation for the Mesos Native Scheduler

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#1107]

**Comment by yanxz** [comment]
Hey I'm trying to play with Mesos scheduler and I'm very interested in running Heron using Mesos Native Scheduler. I can wrap up my practices into this documentation if you guys are fine with it.

**Comment by maosongfu** [comment]
@yanxz That's awesome. I will assign this issue to you.

**Comment by maosongfu** [comment]
Here are steps for trying mesos scheduler locally:

0. Install heron by building latest master from the scratch(The release version does not contain mesos scheduler)
bazel run —config=darwin —verbose_failures — scripts/packages:heron-client-install.sh —user

1. Install mesos locally
https://mesosphere.com/blog/2014/07/07/installing-mesos-on-your-mac-with-homebrew/

2. Change the config in heron/config/src/yaml/conf/mesos/scheduler.yaml
"heron.mesos.native.library.path" to the dir you mesos installed in step 1

3. Play with mesos scheduler
heron submit mesos —verbose ~/.heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology
heron kill mesos ExclamationTopology

**Comment by maosongfu** [comment]
Fixed: #1142

**Comment by objmagic** [comment]
fixed via #1142
