### ISSUE TITLE
use slf4j for logging in Java 

### ISSUE THREAD

**Issue by caofangkun** [twitter/heron#1112]
We use several logging implementation now in the project  as : 
 ``  commons-logging:commons-logging:1.1.1``
 
 `` org.slf4j:slf4j-api:1.7.7 org.slf4j:slf4j-jdk14:1.7.7 ``

``  jdk1.8 java.util.logging ``

We'better use slf4j for logging in Java  
and make it independent of any particular logging implementation.

**Comment by maosongfu** [comment]
Hi,

We had a discussion a long time ago and we decided to use only java.util.logging within heron code base. The existence of any other logging libraries is for other 3rd party libraries that heron uses.
