### ISSUE TITLE
Set PEXROOT to the current working directory

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#1131]
This is needed so that when PEX unzips - the unzipped files get into go into the current working directory. Otherwise, with YARN since users' jobs run as headless, it attempts to decompress in /home - which gives a permission denied errors.

**Comment by mycFelix** [comment]
Sounds great!!! 
Looking forward it~~~

**Comment by objmagic** [comment]
resolved via https://github.com/twitter/heron/pull/1140
