### ISSUE TITLE
WakeableLooper's timer thread safety

### ISSUE THREAD

**Issue by kennylbj** [twitter/heron#1139]
![image](https://cloud.githubusercontent.com/assets/6435874/17076344/c0b96ee2-50e2-11e6-9957-973acc8c4703.png)

The timer of WakeableLooper is implemented by PriorityQueue and never being synchronized. There are two method can modify timer queue: triggerExpiredTimers() and registerTimerEventInNanoSeconds(). 
The trigger method is thread safe because it's invoked in loop().  However the public method registerTimerEventInNanoSeconds() will add element into timer queue. If this method invoked outside the nioLooper thread, it will cause thread unsafety.
I think it's best to use assertInLooop() in the front of registerTimer to gurantee thread safety.
assertInLoop can be simply implemented by comparing current thread id with looper's final thread id.

**Comment by maosongfu** [comment]
Very good question. We discussed this a long time ago.

WakeableLooper is designed non-thread-safe, and we rely on higher level logic to handle this concern. 
For instance, if you take a look at heron-instance source code, you will see there are two threads, Gateway and Slave, and each of them has one WakeableLooper. Data communication between them will be done within a thread-safe Queue, LinkedTransaferQueue; and WakeableLooper will register events in its own thread to listen on that Queue. 
Simply saying, those events-registered interfaces should not be invoked in other threads.

**Comment by kennylbj** [comment]
I've implemented a method to check the thread safety whenever adding event to timer queue. 
https://github.com/kennylbj/heron/blob/master/heron/common/src/java/com/twitter/heron/common/basics/WakeableLooper.java
Maybe get some overhead but gain more safety.

Should i pull a request for that implementation or just remain the current design?

**Comment by maosongfu** [comment]
Let's keep current design for now. It is a low level library shared in a lot of places; need more careful experiments and thoughts. 

For instance, you mentioned "Maybe get some overhead", could we quantify the overhead, in basic library benchmark, simple topoogies and normal production topologies?

**Comment by kennylbj** [comment]
What you say is very reasonable! By the way PriorityQueue seems hard to implement cancel timer.

**Comment by maosongfu** [comment]
`By the way PriorityQueue seems hard to implement cancel timer.`

True. We don't provide interfaces like cancelTimer(..); will definitely review this data structure if we need to add this interface in future.
