### ISSUE TITLE
Dedup and clean up scheduler launch and packing plan creation code

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#1158]
In Heron, Launcher's responsibilities includes packing plan creation and launching Scheduler. A Scheduler can either be client local (e.g. Aurora) or remote (e.g. yarn, mesos). As a result the launcher's code needs to available on the client and on the server. Currently there is some code duplication in the classes performing this job, `SchedulerMain` and `LaunchRunner`. As part of this issue the following can be provided/fixed/

1. I think a utility class `LauncherUtils` is needed which would be used in both server and client side launch paths. 
1. Some launcher related code seems to have spilled into `SchedulerUtils`. This could be moved to `LauncherUtils` too.
1. Remove scheduler related dead code from `heron-executor.py`

**Comment by billonahill** [comment]
`SchedulerMain.runScheduler()` also has overlapping code with `SubmitterMain.submitTopology` (for object initialization).

What dead code are you referring to in `heron-executor.py`?

**Comment by ashvina** [comment]
I do not see any users of this code: https://github.com/ashvina/heron/commit/7b6a5b97b4e1033bbdb21f36ad5fa06474fa8e25
