### ISSUE TITLE
Check if there's any missing dependencies for heron

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#1171]
Reported in #1165, reflectasm is missing due to the upgrade of kryo version. We need to do a complete dependency check for Heron to avoid potential issues.

**Comment by kramasamy** [comment]
@nlu90 - is this done?

**Comment by nlu90** [comment]
@kramasamy yeah, I compared the jars in WORKSPACE file with the old heron repo. Most of the used jars remain the same.
