### ISSUE TITLE
Heron Executor's use of logging module

### ISSUE THREAD

**Issue by taishi8117** [twitter/heron#1216]
Heron Executor currently uses its own print function [``do_print()``](https://github.com/twitter/heron/blob/master/heron/executor/src/python/heron_executor.py#L41), instead of heron's common logging module (``heron/common/src/python/utils/log.py``). In order to make the logging uniform, it's better for the executor to use this as well, but there are several potential issues:

1. Since stdout/stderr of the executor is already redirected to a file (e.g. heron-executor.stdout) by the scheduler, any logs from the executor should be output to stdout. That case, we can't use the existing [``StreamHandler``](https://github.com/twitter/heron/blob/master/heron/common/src/python/utils/log.py#L56), because  ugly escape characters from colorlog will also be in the log file. A possible solution is to create another StreamHandler that doesn't use colorlog.
2. Heron Executor does not use any other common modules (under ``heron/common/src/python``), meaning that importing the whole heron's python common library just for ``log.py`` is quite cumbersome (since it includes unnecessary dependencies, like tornado, as well). One possible solution is to create another BUILD rule for the python common, such as one just for logging. 

What would be the best solution?

Related PR: #1195

**Comment by billonahill** [comment]
For #2 if we want just logging we should do what you suggest and break it
out into its own dep. I suspect as the project evolves more bazel targets
will get more granular to the package level.

**Comment by kramasamy** [comment]
probably good to keep the heron executor simple with minimal dependencies?

**Comment by objmagic** [comment]
I agree with Bill. It's a good idea to introduce more granularity. By the way, you can make a dependency graph on your [tnojima/python_topo](https://github.com/taishi8117/heron/commits/tnojima/python_topo) branch by:

````Bash
$ bazel query 'deps(heron/common/src/python:common)' --output graph > heron-py-common.dot
$ dot -Tpng heron-py-common.dot > heron-py-common.png
````

![heron-py-common](https://cloud.githubusercontent.com/assets/3656079/17444884/31a80212-5af7-11e6-90b4-a6290e24bcb5.png)

**Comment by objmagic** [comment]
Just as a reference, here is the output of command `tree heron/common/src/python/`

````
heron/common/src/python/
├── BUILD
├── basics
│   ├── __init__.py
│   ├── event_looper.py
│   └── gateway_looper.py
├── constants.py
├── handler
│   └── access
│       ├── __init__.py
│       ├── fetch.py
│       ├── heron.py
│       └── query.py
├── network
│   ├── __init__.py
│   ├── heron_client.py
│   ├── protocol.py
│   └── socket_options.py
├── pex_loader.py
└── utils
    ├── __init__.py
    ├── config.py
    ├── log.py
    ├── metrics
    │   ├── __init__.py
    │   ├── metrics.py
    │   └── metrics_helper.py
    ├── misc
    │   ├── __init__.py
    │   ├── communicator.py
    │   ├── custom_grouping_helper.py
    │   ├── outgoing_tuple_helper.py
    │   ├── pplan_helper.py
    │   └── serializer.py
    ├── topology
    │   ├── __init__.py
    │   ├── custom_grouping.py
    │   ├── task_hook.py
    │   └── topology_context.py
    ├── tracker_access.py
    └── tuple.py

8 directories, 32 files
````

**Comment by objmagic** [comment]
Besides introducing more granularity (adding `BUILD` file per subdirectory), I think we should also be careful on when to include dependency `//heron/proto:proto-py`. Please identify precisely the **subdirectories** that require Protobuf. Do not add Protobuf dependency on toplevel BUILD file under `heron/common/src/python`.

**Comment by objmagic** [comment]
@taishi8117 Do you think #1252 resolved this issue completely?

**Comment by taishi8117** [comment]
@objmagic yes, it should.
