### ISSUE TITLE
No handlers could be found for logger "root"

### ISSUE THREAD

**Issue by kylozw** [twitter/heron#1280]
I installed heron following [Quick Start Guide](http://twitter.github.io/heron/docs/getting-started/), but when I run the `heron version`. 
This error occurred:
`No handlers could be found for logger "root"`

**Comment by kramasamy** [comment]
@kylozw - this issue has been reported sporadically. We did a fix and is in the master. If you compile and install from the master, the issue should go away. Please try it and let us know.

**Comment by kylozw** [comment]
When I built packages on ubuntu, the following happened:
```
ERROR: missing input file '//scripts/compile:env_exec.sh'.
ERROR: /usr/local/heron/heron/schedulers/tests/java/BUILD:132:1: Creating runfiles tree bazel-out/local-fastbuild/bin/heron/schedulers/tests/java/MesosFrameworkTest.runfiles failed: build-runfiles failed: error executing command /root/.cache/bazel/_bazel_root/ea5f5d1d1e31949bd99eb97a82759a2c/execroot/heron/_bin/build-runfiles bazel-out/local-fastbuild/bin/heron/schedulers/tests/java/MesosFrameworkTest.runfiles_manifest ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /usr/local/heron/third_party/yaml-cpp/BUILD:11:1: //third_party/yaml-cpp:yaml-cpp-srcs: missing input file '//scripts/compile:env_exec.sh'.
ERROR: /usr/local/heron/third_party/yaml-cpp/BUILD:11:1 1 input file(s) do not exist.
```

**Comment by objmagic** [comment]
should be resolved in https://github.com/twitter/heron/pull/1276

**Comment by kramasamy** [comment]
When building - you need to first configure bazel. You need to run

./bazel_configure.py

Cheers
/Karthik

**Comment by objmagic** [comment]
@kylozw if you have any other question, you can open a separate issue or ask on Heron's [mailing list](https://groups.google.com/forum/#!forum/heron-users)

**Comment by objmagic** [comment]
closing this issue since I believe this problem is gone.
