### ISSUE TITLE
Heron-tracker doesn't work in docker-compose mode

### ISSUE THREAD

**Issue by waitingkuo** [twitter/heron#1310]
I followed <https://github.com/twitter/heron/tree/master/docker> to launch some heron containers.

```
willy@willy-heron:~/heron$ ./docker/start-docker.sh heron:testbuild-ubuntu14.04
Launching heron tracker, ui, and local executor env with docker-compose
    using image heron:testbuild-ubuntu14.04...
(only sample topologies will be available for submission; mount additional volumes to heron-executor to make additional topologies available for submission)

Creating heron_tracker_1
Creating heron_ui_1
Creating heron_executor_1
Example topologies are available in /usr/local/heron/examples/heron-examples.jar

To submit a topology:
        docker exec heron_executor_1 heron submit local /usr/local/heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology --deploy-deactivated
To activate a topology:
        docker exec -it heron_executor_1 heron activate local ExclamationTopology
To kill a topology:
        docker exec -it heron_executor_1 heron kill local ExclamationTopology
-------------------
To shutdown heron daemons: docker-compose -p heron stop
-------------------
```

But heron-track didn't work until I created the first topology. 

```
willy@willy-heron:~/heron$ docker logs heron_tracker_1
INFO: 08/29/2016 14:28:15 +0000 Connecting to file state with rootpath: /root/.herondata/repository/state/local
INFO: 08/29/2016 14:28:15 +0000 Tracker has started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "heron/statemgrs/src/python/filestatemanager.py", line 111, in monitor
    lambda f: os.path.isfile(os.path.join(topologies_path, f)), os.listdir(topologies_path))
OSError: [Errno 2] No such file or directory: '/root/.herondata/repository/state/local/topologies'

INFO: 08/29/2016 14:28:15 +0000 Running on port: 8888
INFO: 08/29/2016 14:28:15 +0000 Using config file: /usr/local/herontools/conf/heron_tracker.yaml
```

After I launched the first topology, the directory `/root/.herondata/repository/state/local/topologies` is made. At this moment we can restart the `heron-tracker` container again to make it work.

Need we add something like `mkdir /root/.herondata/repository/state/local/topologies` before running `heron-tracker`?

**Comment by objmagic** [comment]
I cannot reproduce this problem on OS X. Will try Docker some time...

**Comment by waitingkuo** [comment]
@objmagic Did you delete the `heron_herondata` volume first?

**Comment by objmagic** [comment]
Ah, I see. If I do `rm -rf ~/.herondata`, I can see the problem.

There are three solutions that I can think of:
1. do `mkdir` as you said in `filestatemanager.py`
2. do `mkdir` when we install Heron, just like how we create `~/.heron` and `~/.herontools`
3. emit an useful error message to tell user that he needs to run a topology

**Comment by waitingkuo** [comment]
In this docker-compose file, to share .herondata among multiple containers, that directory is mounted as a docker volume. So it's hard create the directory when installing. One quick hack to the docker-compose is wrap creating dir & running heron-track as one command when running heron-track container:

```
tracker:
    image: ${HERON_IMAGE}
    command: bash -c "mkdir -p /root/.herondata/repository/state/local/topologies; heron-tracker"
    ports:
      - "8888:8888"
    hostname: tracker
    networks:
      - heron
    volumes:
      - "herondata:/root/.herondata"
```

This works but I believe we need to find a better way to do so.

**Comment by kramasamy** [comment]
@waitingkuo - I think the actual fix could be for the tracker to wait until those directories/zk nodes are created by polling every second. Once we have this - independent of whether the tracker starts first or later, it will correctly.

**Comment by waitingkuo** [comment]
@kramasamy - Just checked the code. 

```
topologies = filter(     
    lambda f: os.path.isfile(os.path.join(topologies_path, f)), os.listdir(topologies_path))
```

It intends to collect the topologies every few seconds. How about modifying as

```
topologies = []
if os.path.isdir(topologies_path):
    topologies = filter(     
        lambda f: os.path.isfile(os.path.join(topologies_path, f)), os.listdir(topologies_path))
```
If the path isn't existed, just returns a empty array.

Could you give me a hint that how I build this tool via Bazel without building all the codes.

**Comment by kramasamy** [comment]
@waitingkuo - sure please try this out. If you want to just install the tools, do the following 

bazel run --config=<your-platform> -- scripts/packages:heron-tools-install.sh --user 

and then run heron-tracker and heron-ui before launching topologies and see if that works.

**Comment by waitingkuo** [comment]
docker-compose work normally after I add this

**Comment by kramasamy** [comment]
Please send a pull request

**Comment by waitingkuo** [comment]
@kramasamy  sent, #1312
