### ISSUE TITLE
some demo codes are not visible in heron-tracker-api

### ISSUE THREAD

**Issue by tobecontinued** [twitter/heron#1328]
When I access http://twitter.github.io/heron/docs/operators/heron-tracker-api/#metricsquery. the demo codes are not visible if I not select them， here is the pic.
![image](https://cloud.githubusercontent.com/assets/3350874/18198845/5d0ab978-7130-11e6-8cff-e3ada085c13b.png)

**Comment by objmagic** [comment]
resolved in #1331 but we will rebuild the website later.
