### ISSUE TITLE
Executor is ignoring local state manager location

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#1343]
This issue is related to #1313 (dbe0563)

In a test I am running YARN scheduler on a single node with local state manager (config below)
```
heron.class.state.manager:        com.twitter.heron.statemgr.localfs.LocalFileSystemStateManager
heron.statemgr.connection.string: LOCALMODE
heron.statemgr.root.path:         ${HOME}/.herondata/repository/state/${CLUSTER}
``` 

Here `CLUSTER = yarn`

The state manager is persisting topology and packing plans at the correct location, under ~/.herondata/repository/state/**yarn**. 

However the executor seems to be looking for the packing plan under a different location (~/.herondata/repository/state/**local**). Here is the relevant info from the executor logs:
```
...
09/05/2016 11:20:41 -0700:INFO: state manager configs: {'hostport': 'LOCALMODE', 'type': 'file', 'name': 'local', 'tunnelhost': 'localhost', 'rootpath': '~/.herondata/repository/state/local'}
09/05/2016 11:20:41 -0700:INFO: Connecting to file state with rootpath: /home/.herondata/repository/state/local
...
```

As a result executor fails to start any processes.

**Comment by objmagic** [comment]
@billonahill 

Maybe because of this if expression should not be nested? https://github.com/twitter/heron/commit/dbe056322528ea034e5f84c7f52e000a00738092#diff-2a669e084143b86b5766a49245f8e357R620

**Comment by billonahill** [comment]
Ugh, yeah that's the problem. The statemanager config loading is not in the shape I'd like it to be. The issue is that the python state managers take configs in a different format than the java state managers and we have configs for the latter so we need to read them and convert to the former.

We can't just read the configs directly, because the java impl has wildcard parsing logic not present in the python impl. For example, for the local statemanager the config is this:
```
$ grep heron.statemgr.root.path ~/.heron/conf/local/statemgr.yaml
heron.statemgr.root.path:                       ${HOME}/.herondata/repository/state/${CLUSTER}
```
where `${CLUSTER}` and `${HOME}` are not handled. What we need is a python implementation of https://github.com/twitter/heron/blob/master/heron/spi/src/java/com/twitter/heron/spi/common/Misc.java#L142

Anyone know if there's anything similar in python?

**Comment by objmagic** [comment]
@billonahill 

How about using [`os.sep`](https://docs.python.org/3/library/os.html#os.sep) to split path and substituting wildcard variable with corresponding variable in config?

**Comment by billonahill** [comment]
I'm going to take a stab at this. I suspect there are wildcard heron variables that we don't have access to in python like we do in java, but let me see how much we can support.

**Comment by ashvina** [comment]
@billonahill 
Is the user expected to configure ${HOME} in some config file? The path is getting resolved incorrectly:
```
 09/08/2016 22:31:45 -0700:INFO: Logging pid 50263 to file heron-executor-0.pid
 09/08/2016 22:31:45 -0700:INFO: Connecting to file state with rootpath: /home//.herondata/repository/state/yarn
 09/08/2016 22:31:45 -0700:INFO: Registered state watch for packing plan changes with state manager <heron.statemgrs.src.python.filestatemanager.FileStateManager object at 0x10f8db450>.
 09/08/2016 22:31:45 -0700:INFO: State watch triggered for packing plan change. New PackingPlan:
```

**Comment by billonahill** [comment]
@ashvina no ideally the user should have to. There are different ways to determine the home dir in python, we're using 
```
home_dir = os.getenv('HOME')
```
See https://github.com/twitter/heron/blob/master/heron/statemgrs/src/python/configloader.py#L29

We could change that approach though. Could you see if this resolves correctly in your environment:
```
from os.path import expanduser
home = expanduser("~")
```

**Comment by ashvina** [comment]
@billonahill Thanks for the pointers.
This issue is similar to one seen in #1140. Many times YARN application is headless and there is no home directory for the user. In my test case, YARN set the home as /home. I can thinking of fixing the issue by updating the YARN configuration for now. But I am not sure if resolving the path on the executor is a good idea. What do you think about constructing the state manager directory location on the client and let all components use the same?

**Comment by billonahill** [comment]
The `${HOME}` wildcard token is supported and used extensively by Heron in the java classes, as most files under https://github.com/twitter/heron/blob/master/heron/config/src/yaml/conf show. I don't think we should deviate from that approach just for the python statemanger use case. Yarn must be able to load this path currently for [java](https://github.com/twitter/heron/blob/master/heron/config/src/yaml/conf/yarn/statemgr.yaml#L8) so we should be able to do the same for python.
