### ISSUE TITLE
Troubles across the installation (Ubuntu)

### ISSUE THREAD

**Issue by jomsdev** [twitter/heron#1355]
Hello guys,

I tried to install the library in Ubuntu (14.04 and 16.04) without much success last week. The problem was #1280 in both versions. Finally, I decided to build it from source. However, there are two steps missed in the documentation. I did it from a fresh Ubuntu image and then I had to:

- `JAVA_HOME`: set before compiling.
- Python development tools: install python-dev and python-pip before run bazel.

It's no big deal. However, I think we could include that steps in the documentation to save time for the users.

I just added it and made the pull request  #1356 , if something is missed/wrong let me now.

Thanks,

Jordi.

**Comment by kramasamy** [comment]
@jomsdev - just wondering if this is tried in 0.14.2

**Comment by jomsdev** [comment]
I did it yesterday clonging from the master branch

**Comment by objmagic** [comment]
@jomsdev Logger problem should be fixed via https://github.com/twitter/heron/pull/1276 which was after 0.14.2

**Comment by jomsdev** [comment]
@objmagic - Only to be sure that it was the 0.14.02 version I repeated it. Same problem 

> No handlers could be found for logger "root"

I installed a fresh ubuntu version and then installed java using the apt-get default-jre default-jdk. That's all.

**Comment by kramasamy** [comment]
@jomsdev - just wondering if this issue is resolved. if so we can close this.

**Comment by jomsdev** [comment]
I could install it compiling it from source. However, using the script that you provide (0.14.02) I couldn't. It was using a fresh Ubuntu. 

I would close it and take it into account only if anyone else complains about the same problem.

**Comment by kramasamy** [comment]
If you could please try with 0.14.3 and see if that works or not. Then we can close the issue

**Comment by jomsdev** [comment]
I just tried it and it is working now, we can close the issue.
