### ISSUE TITLE
bazel compiles heron failed

### ISSUE THREAD

**Issue by Au80** [twitter/heron#1368]
I build Heron on CentOS 7, my system information is 
[rjfh@au heron-0.14.2]$ uname -a
Linux au 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux,

I follow the steps in http://twitter.github.io/heron/docs/developers/compiling/linux/#building-on-centos-7, I run Step 6, something is wrong.

```
[rjfh@au heron-0.14.2]$ ./bazel_configure.py
Platform Linux
Using C compiler          :     /usr/bin/gcc (4.8.5)
Using C++ compiler        :     /usr/bin/g++ (4.8.5)
Using C preprocessor      :     /usr/bin/cpp (4.8.5)
Using C++ preprocessor    :     /usr/bin/cpp (4.8.5)
Using linker              :     /usr/bin/ld.bfd
Using Automake            :     /usr/bin/automake (1.13.4)
Using Autoconf            :     /usr/bin/autoconf (2.69)
Using Make                :     /usr/bin/make (3.82)
Using CMake               :     /usr/bin/cmake (2.8.11)
Using Python2             :     /usr/bin/python2.7 (2.7.5)
Using archiver            :     /usr/bin/ar
Using coverage tool       :     /usr/bin/gcov
Using dwp                 :     /usr/bin/dwp
Using nm                  :     /usr/bin/nm
Using objcopy             :     /usr/bin/objcopy
Using objdump             :     /usr/bin/objdump
Using strip               :     /usr/bin/strip
Wrote the environment exec file scripts/compile/env_exec.sh

next run the command bazel build --config=centos heron/...
[rjfh@au heron-0.14.2]$ bazel build --config=centos heron/...
INFO: Found 385 targets...
ERROR: Process exited with status 1.
INFO: Elapsed time: 4.307s, Critical Path: 2.69s
```

I have installed libunwind, bazel.

```
[rjfh@au heron-0.14.2]$ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392
```

My Java version is 1.8.0_102.

```
[rjfh@au heron-0.14.2]$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

Is there someone can tell me why I build failed?
Thanks!

**Comment by kramasamy** [comment]
@au80 - Can you try the following?

```
bazel build --config=centos --verbose_failures heron/...
```

it give an idea what caused the failure.

**Comment by Au80** [comment]
@kramasamy I run bazel build --config=centos --verbose_failures heron/... , but nothing more shows.

[rjfh@au heron-0.14.2]$ bazel build --config=centos --verbose_failures heron/...
INFO: Found 385 targets...
ERROR: Process exited with status 1.
INFO: Elapsed time: 1.359s, Critical Path: 0.25s

**Comment by kramasamy** [comment]
@Au80 - weird, we did not encounter such an issue. How about checking the docker/Dockerfile.centos7  file and see if all the software that is being installed in there is available in your machine?

**Comment by Au80** [comment]
@kramasamy I have checked the software versions which are needed by building Heron, versions match requirements.
Bazel = 0.3.0. 
Java 8 
Autoconf >= 2.6.3
Automake >= 1.11.1
GNU Make >= 3.81
GNU Libtool >= 2.4.6
gcc/g++ >= 4.8.1 (Linux platforms)
CMake >= 2.6.4
Python >= 2.7 (not including Python 3.x)
Perl >= 5.8.8

Before I rebuild Heron, I have ran the command 
sudo yum install gcc gcc-c++ kernel-devel wget unzip zlib-devel zip git automake cmake patch libtool -y
and 
yum -y update
and 
yum groupinstall "Base" "Development Libraries" "Development Tools".

How can I check the docker/Dockerfile.centos7 file to sure softwares in my machine are available that I have installed .

**Comment by kramasamy** [comment]
@Au80  - Can you use docker to build your centos build and see if it works? Check the documentation in the following URL and follow the directions - for compiling from source

https://github.com/twitter/heron/tree/master/docker

**Comment by Au80** [comment]
@kramasamy - I have sured my Docker is well installed.
[rjfh@au heron-0.14.2]$ docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.
To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash
Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com
For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

I followed documentation in https://github.com/twitter/heron/tree/master/docker, I run the command
./docker/build-artifacts.sh centos 7.2 /home/rjfh/downloads/heron-0.14.2.tar.gz /home/rjfh/downloads/output/heron-0.14.2
[rjfh@au heron-0.14.2]$ pwd
/home/rjfh/downloads/heron-0.14.2
[rjfh@au heron-0.14.2]$ ./docker/build-artifacts.sh centos 7.2 /home/rjfh/downloads/heron-0.14.2.tar.gz /home/rjfh/downloads/output/heron-0.14.2
Creating output directory /home/rjfh/downloads/output/heron-0.14.2
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
The Dockerfiler /home/rjfh/.heron-compile/Dockerfile.centos does not exist

I alse list the files in directory /home/rjfh/.heron-compile/
[rjfh@au heron-0.14.2]$ ll /home/rjfh/.heron-compile/
total 52
-rwxrwxr-x. 1 rjfh rjfh 3160 Sep 11 12:43 build-artifacts.sh
-rwxrwxr-x. 1 rjfh rjfh 1167 Sep 11 12:43 build-docker.sh
-rwxrwxr-x. 1 rjfh rjfh  223 Sep 11 12:43 cleanup-dockers.sh
-rwxrwxr-x. 1 rjfh rjfh 1365 Sep 11 12:43 compile-docker.sh
-rwxrwxr-x. 1 rjfh rjfh 1502 Sep 11 12:43 compile-platform.sh
-rw-rw-r--. 1 rjfh rjfh  711 Sep 11 12:43 docker-compose.yml
-rw-rw-r--. 1 rjfh rjfh 1379 Sep 11 12:43 Dockerfile.centos7
-rw-rw-r--. 1 rjfh rjfh  827 Sep 11 12:43 Dockerfile.dist.ubuntu14.04
-rw-rw-r--. 1 rjfh rjfh 1140 Sep 11 12:43 Dockerfile.ubuntu14.04
-rw-rw-r--. 1 rjfh rjfh 1140 Sep 11 12:43 Dockerfile.ubuntu15.10
-rw-rw-r--. 1 rjfh rjfh 1291 Sep 11 12:43 Readme.md
-rwxrwxr-x. 1 rjfh rjfh 1102 Sep 11 12:43 start-docker.sh
-rwxrwxr-x. 1 rjfh rjfh   71 Sep 11 12:43 stop-docker.sh

The Dockerfiler /home/rjfh/.heron-compile/Dockerfile.centos does not exist, but Dockerfile.centos7 exists. What is wrong?

**Comment by kramasamy** [comment]
the command should be 

```
docker/build-artifacts.sh centos7 master ~/heron-centos
```

In the above command, 

* centos7 is the platform for which the Dockerfile.centos7 exists, 
* master represents the version since you are building from the master (but you can give anything)
* heron-centos - is the name of the output directory where the final packages will be stored.

Hope this helps.

**Comment by Au80** [comment]
@kramasamy - Forgive my stupid mistake. Thank you for your valuable time.  Thank you for your constant help and patience.  Unfortunately, I guess I am still failed.

INFO: From Executing extra_action //tools/java:checkstyle_java on //third_party/java:jarjar:
Starting audit...
Audit done.
INFO: From Executing extra_action //tools/python:checkstyle_python on //heron/shell/src/python:heron-shell:
Sep 11, 2016 9:28:42 AM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 2 python files found by checkstyle
INFO: From Executing extra_action //tools/python:checkstyle_python on //heron/executor/src/python:heron-executor:
Sep 11, 2016 9:28:44 AM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 8 python files found by checkstyle
INFO: From Executing extra_action //tools/python:checkstyle_python on //heron/explorer/src/python:heron-explorer:
Sep 11, 2016 9:28:43 AM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 45 python files found by checkstyle
INFO: From Executing extra_action //tools/python:checkstyle_python on //heron/ui/src/python:heron-ui:
Sep 11, 2016 9:28:45 AM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 45 python files found by checkstyle
INFO: From Executing extra_action //tools/python:checkstyle_python on //heron/tracker/src/python:heron-tracker:
Sep 11, 2016 9:28:42 AM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 70 python files found by checkstyle
[1,195 / 1,200] Still waiting for 1 job to complete:
[1,195 / 1,200] Still waiting for 1 job to complete:
      Running (standalone):
        PexPython heron/cli/src/python/heron.pex, 6323 s
^CCleaning up scratch dir

**Comment by kramasamy** [comment]
@Au80 - it looks like you aborted it in the middle with ^C. Is that correct? It takes ~20 mins compile actually.

**Comment by Au80** [comment]
@kramasamy - In the log, PexPython heron/cli/src/python/heron.pex, 6323 s, I think something have gone wrong, so I press ^C.

**Comment by kramasamy** [comment]
@Au80 - are you connected to internet, while compiling? We download a bunch of jar packages, python packages which compiling.

**Comment by Au80** [comment]
@kramasamy - I am sure I can access internet, but I can't know which site is restricted because of some reasons.
[1,195 / 1,200] Still waiting for 1 job to complete: 
Running (standalone): PexPython heron/cli/src/python/heron.pex, 6323 s

The building is always waiting for [1,195 / 1,200]  job is always to complete.
