### ISSUE TITLE
Saving `today-start-offset` offset in Kafka-spout

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1383]
hi~ guys

We use Storm to count some quotas in our Realtime-BI system. Kafka is our main data source and its offset was saved on zookeeper.

In our scenarios, users may want to recompile & resubmit topo from specific offset such as `today-start-offset` due to kafka data fault, so that statistical indicators can be re-calculated with the right topo.

So we save the `today-start-offset` offset on the zookeeper. Then, users can use `cli-command` to modify the offset-data on zookeeper and restart the topo once user wants to trace back.

`today-start-offset` means the `offset` of the start time of the current day.

For an example:
if the offset on `2016-09-13 00:00:00` is 1000,then we write {"todayStartOffset":1000} to zookeeper.

Is Heron interested in this?

**Comment by kramasamy** [comment]
@mycFelix - Definitely, it is an interesting use case. However, this is more embedded in the application logic, isn't?

**Comment by mycFelix** [comment]
@kramasamy - Thank you for your response.

This issue comes from our working scenario. Our team has to figure it out in case Kafka data or topology is wrong.

Kafka-spout will commit current offset automatic. Our main work is for making every topology which consumes data from Kafka saves `today-start-offset` on the zookeeper automatic too. What we need to do is identifying daily-change and save the offset. Then every topology which uses Kafka-spout is able to be traced back to `today-start-offset` by following steps.

* deactive topology
* change `kafka-offset` data on zookeeper using `zookeeper-cli-command`
* rebalence/restart topology

**Comment by kramasamy** [comment]
@mycFelix - As far as I remember, Kafka spout used to store the offsets in ZK. That became a source of issue for us. At a large scale, the spouts were hitting ZK hard that ZK was unable to keep up. The functionality of ```today-start-offset``` is with the spouts isn't? - since the spouts are the ones that read the offset actually isn't?

**Comment by mycFelix** [comment]
@kramasamy - We met the problem you mentioned too, which brought us a lot of trouble. Indeed, the functionality of `today-start-offset` is with the spouts. Every topology commits offset to ZK. What we need to do is adding `today-start-offset` key-value to the json data. We did not increase the number of write times. What we increased is the number of bytes of json data.

But every topology writes `today-start-offset` once per day with the e and never read it from ZK. So we decided to make a change.

**Comment by mycFelix** [comment]
@kramasamy - We met the problem you mentioned too, which brought us a lot of trouble. Indeed, the functionality of `today-start-offset` is with the spouts. 

Currently What kafka-spout stores is following:
````
Map<Object, Object> data = (Map<Object, Object>) ImmutableMap.builder()
          .put("topology", ImmutableMap.of("id", topologyInstanceId,
              "name", stormConf.get(Config.TOPOLOGY_NAME)))
          .put("offset", lastCompletedOffset)
          .put("partition", partition.partition)
          .put("broker", ImmutableMap.of("host", partition.host.host,
              "port", partition.host.port))
          .put("topic", partition.topic).build();
````

Topology commits offset to ZK. What we need to do is adding `today-start-offset` key-value to the map data. We do not increase the number of write times. What we increased is the number of bytes of map data.

Topology will never read the key `today-start-offset`  from the ZK on its own. When something goes wrong, we modify the `today-start-offset` value to the `offset` value by `zk-cli-command` and restart the topology. Spouts will read the `offset` value from ZK and restart.

The `today-start-offset`  just gives our user a chance to change their topology and re-calculated the statistical indicators.
