### ISSUE TITLE
set-intellji.sh missing file compile:env_exec.sh

### ISSUE THREAD

**Issue by wangli1426** [twitter/heron#1417]
When running `scripts/setup-intellji.sh` the following error occurs if `bazel_configure.py` has not been run.

```
changing to /home/robert/code/heron/scripts/..
INFO: Found 453 targets...
ERROR: missing input file '//scripts/compile:env_exec.sh'.
```

We should fix the script to check for `scripts/compile:env_exec.sh` and fail with helpful output if not found.

**Comment by maosongfu** [comment]
Solved at #1429
