### ISSUE TITLE
heron on yarn : reef-job-xxxx.jar does not exist

### ISSUE THREAD

**Issue by silence-liu** [twitter/heron#1442]
Failed to run Test Topology on yarn cluster!

Error log :
org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService: { file:/tmp/2016_09_28_14_48_07_reef-job-1/reef-job-8790805129276842877.jar, 1475045292000, ARCHIVE, null } failed: File file:/tmp/2016_09_28_14_48_07_reef-job-1/reef-job-8790805129276842877.jar does not exist
java.io.FileNotFoundException: File file:/tmp/2016_09_28_14_48_07_reef-job-1/reef-job-8790805129276842877.jar does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:606)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:819)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:596)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
	at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:253)
	at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:63)

![image](https://cloud.githubusercontent.com/assets/20079928/18904619/a48d6eec-8591-11e6-8c69-9513a4e3143f.png)

config setting :
![image](https://cloud.githubusercontent.com/assets/20079928/18904875/e1f99cfa-8592-11e6-98c5-e5f787f83f61.png)
![image](https://cloud.githubusercontent.com/assets/20079928/18904888/eb81ec3c-8592-11e6-8f22-73c9a3b3ff1c.png)
![image](https://cloud.githubusercontent.com/assets/20079928/18904896/fd99b454-8592-11e6-8845-12ba708cc629.png)

yarn log:
![image](https://cloud.githubusercontent.com/assets/20079928/18904657/e55f49a4-8591-11e6-8613-c68db07bee14.png)

**Comment by ashvina** [comment]
@silence-liu The YARN scheduler does not depend on HDFS uploader. It instead uses the file system configured in `core-site.xml`. Please make sure `core-site.xml` is in the client's class path and is correctly configured. In this case the scheduler failed to find reef job on the AM (`/tmp/2016_09_28_14_48_07_reef-job-1/reef-job-8790805129276842877.jar`). Missing `core-site.xml` is the most likely issue.

**Comment by mycFelix** [comment]
@silence-liu as @ashvina mentioned,please make sure the right config. And would you like to share your Heron version? if you are using 0.14.3, you can follow the guide https://github.com/twitter/heron/blob/master/website/content/docs/operators/deployment/schedulers/yarn.md . The website will be updated soon.

**Comment by silence-liu** [comment]
@mycFelix @ashvina 
Thank you for your suggestion. this problem is solved! because the core-site.xml not in classpath.
but i meet new problem..
![image](https://cloud.githubusercontent.com/assets/20079928/18944356/a348c3f8-8657-11e6-8c6e-2114e2900b67.png)
![image](https://cloud.githubusercontent.com/assets/20079928/18944480/6641dbb0-8658-11e6-9e97-a7d65cbb445d.png)

**Comment by mycFelix** [comment]
You are welcome
Please close the issue if it was solved

**Comment by silence-liu** [comment]
@mycFelix @ashvina  

Thanks for help~~
