### ISSUE TITLE
Missing Storm API: IMetricsConsumer

### ISSUE THREAD

**Issue by vbhavsar** [twitter/heron#1443]
One of the teams at Spotify uses a custom Storm metrics consumer that implements `backtype.storm.metric.api.IMetricsConsumer`. This interface is missing from the Heron API. 

The ask is to add support for this API to avoid code changes.

**Comment by maosongfu** [comment]
#1445

**Comment by maosongfu** [comment]
Resolved.

**Comment by vbhavsar** [comment]
That was super fast. Thank you!
