### ISSUE TITLE
Update topology should validate that requested parallelism is not what exists

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1455]
Currently if parallelism = X and the user requests to change parallelism to X, we go through a scalding event. We should instead return messaging that the parallelism is already set to X and halt.

**Comment by kramasamy** [comment]
@billonahill - is this completed or should be moved to subsequent releases?

**Comment by billonahill** [comment]
This is not completed and can move to a subsequent release if not done by 0.14.4.
