### ISSUE TITLE
Why python topology 20-40 times slow than java?

### ISSUE THREAD

**Issue by yunfan123** [twitter/heron#1484]
Because cost of serialization? Or other issues? Which version of heron can fix it?

**Comment by objmagic** [comment]
we did some basic investigation and believe it's because of the inefficiency of Python Protobuf library.

**Comment by billonahill** [comment]
Please pose questions like this on the mailing list instead if filing issues.

**Comment by objmagic** [comment]
And please use mailing list if you have more questions: https://groups.google.com/forum/#!forum/heron-users
