### ISSUE TITLE
topology works in development but has problems after submit

### ISSUE THREAD

**Issue by AMirFirouzi** [twitter/heron#1535]
i recently wrote a topology, and when i run it in development mode(via intelliJ) it runs perfectly fine and generate the output. but when i submit it to heron-cli (in a local cluster on a single machine-kubuntu14.04), after activation, it seems to be running and shows the plans in the UI but doesn't generate any output and shows no emitted tuples in UI.

any idea what could be the problem?
thanks

**Comment by AMirFirouzi** [comment]
actually i found the source of the problem, it was the path to input file, i was using relative paths and when submitting to cluster it couldn't find the file.
what is the correct way to get input files? we should specify it in the input arguments when submitting topologies?

**Comment by objmagic** [comment]
because input file is only on your local machine but not on the cluster machine?

**Comment by billonahill** [comment]
If your spout or bolt needs to read an input file, you'll need to know how to reference it either relatively or absolutely on the container for which you're running. This logic is specific to what works for your application and your deployed environment.
