### ISSUE TITLE
Missing tuple-serialization-time-ns metric

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#1545]
It looks like in [this commit](https://github.com/twitter/heron/commit/557c9804af0c23952b3df7e29715f01e338884f8#diff-104e33dbd606b8e4ed4639a789160341L210) the call to record the tuple serialization metric for both the spout and the bolt was removed. The latency is still being computed but `serializeDataTuple(streamId, latency);` is no longer being called meaning that metric does not exist in the latest release.

**Comment by objmagic** [comment]
cc @congwang

**Comment by ajorgensen** [comment]
@congwang why was this closed? Was it fixed somewhere else or are you closing as will not fix?

**Comment by objmagic** [comment]
@ajorgensen resolved via https://github.com/twitter/heron/pull/1549

**Comment by ajorgensen** [comment]
@objmagic awesome thanks. @congwang thanks for fixing this!
