### ISSUE TITLE
order_unittest sometimes timeout

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1559]
``//heron/common/tests/cpp/network:order_unittest``

**Comment by objmagic** [comment]
`//heron/common/tests/cpp/network:switch_unittest` also sometimes times out. Maybe mark all tests under `//heron/common/tests/cpp/networ` as flaky so that Bazel could rerun them?

**Comment by huijunw** [comment]
made an issue to separate order_unittest and switch_unittest in #1810
