### ISSUE TITLE
Ack does not work in WordCountTopology example

### ISSUE THREAD

**Issue by wangli1426** [twitter/heron#1568]
I noticed that tuples are acked in the ``ConsumerBolt``, but the ``Ack count`` displayed on web ui is always 0.

To enable ack, we should specify a message id when calling emit in spout.

**Comment by wangli1426** [comment]
Or, alternatively, we can remove the ack() statement in the ``ConsumerBolt`` to avoid misleading the users.

**Comment by wangli1426** [comment]
Since how to use ack is demonstrated in ``AckingTopology``, I believe it's better to remove the ``ack()`` statement in the ``ConsumerBolt``.

**Comment by maosongfu** [comment]
The example to use ack is in `AckingTopology`: https://github.com/twitter/heron/blob/master/heron/examples/src/java/com/twitter/heron/examples/AckingTopology.java
And WordCountTopology is not aimed at that.

**Comment by wangli1426** [comment]
@maosongfu I agree. So I closed the RP for the first approach.
