### ISSUE TITLE
restart.py should use cli_helper

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1594]
it seems that [`restart.py`](https://github.com/twitter/heron/blob/master/heron/tools/cli/src/python/restart.py) can invoke [`cli_helper.py`'s `run`](https://github.com/twitter/heron/blob/master/heron/tools/cli/src/python/cli_helper.py#L50), just like [`kill.py`](https://github.com/twitter/heron/blob/master/heron/tools/cli/src/python/kill.py#L50)

cc @billonahill

**Comment by objmagic** [comment]
I see, because we need to pass `--component_parallelism` to `RuntimeManagerMain`. Same with `restart.py` which needs to pass extra argument `--container-id`.

But I think there is chance we can refactor this.

**Comment by billonahill** [comment]
There's a lot of duplicate code with only subtle difference in how we run. Seems like it could be refactored to be more extensible, or cli_helper.run could really be made into a _class_ that knows how to run the RuntimeManager class (as opposed to a helper method), which could be extended for customizations that some commands might need. Such an OO approach would be nice than the procedural code that exists now.

**Comment by objmagic** [comment]
@billonahill agree that OO approach is nice. will PR.

**Comment by objmagic** [comment]
although #1571 is getting too large, i think it is a good chance to resolve this issue in #1571 since #1571 already involves changes of `restart.py` and `update.py`.

**Comment by objmagic** [comment]
resolved in https://github.com/twitter/heron/pull/1571/commits/cc99a7868303f5952afef3629fc50dba245f49ec in #1571
