### ISSUE TITLE
LaunchRunner implements Callable interface

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1596]
See [LaunchRunner.java](https://github.com/twitter/heron/blob/master/heron/scheduler-core/src/java/com/twitter/heron/scheduler/LaunchRunner.java#L36)

Any particular reason for this? @maosongfu

**Comment by maosongfu** [comment]
It provides the flexibility to run it in a separate thread to enhance performance.

**Comment by objmagic** [comment]
But seems that we don't run it in a separate thread so far?

On Dec 7, 2016, at 09:52, Maosong Fu <notifications@github.com> wrote:

It provides the flexibility to run it in a separate thread to enhance
performance.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/twitter/heron/issues/1596#issuecomment-265519855>, or mute
the thread

**Comment by maosongfu** [comment]
Yes we found that running it in the same thread can provide acceptable performance so far.

**Comment by objmagic** [comment]
refactored so that `LaunchRunner` no longer implements `Callable` in https://github.com/twitter/heron/pull/1571
