### ISSUE TITLE
Duplicated code is found in SubmitterMain.java and SchedulerConfig.java

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1597]
Hi

There is a duplicated code in [SubmitterMain.java](https://github.com/twitter/heron/blob/master/heron/scheduler-core/src/java/com/twitter/heron/scheduler/SubmitterMain.java#L66) and [SchedulerConfig.java](https://github.com/twitter/heron/blob/master/heron/spi/src/java/com/twitter/heron/spi/utils/SchedulerConfig.java#L48).

Is it necessary to add an new method named `FileUtils.getPkgType(String topologyBinaryFile)` in `FileUtils`?   If so, I'll send PR for this.

**Comment by kramasamy** [comment]
Sure - go for it.

**Comment by objmagic** [comment]
resolved via #1599 and #1609
