### ISSUE TITLE
Replace `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8`

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1598]
Hi，

Is it necessary to replace `Charset.forName("UTF-8")` or some codes like `new InputStreamReader(is, "UTF-8")` to the constant variable `StandardCharsets.UTF_8` which JDK 7 has provided

```java
public final class StandardCharsets {
 ……………………

/**
     * Eight-bit UCS Transformation Format
     */
    public static final Charset UTF_8 = Charset.forName("UTF-8");
………………
}
```

**Comment by kramasamy** [comment]
@maosongfu - can you respond?

**Comment by billonahill** [comment]
+1, better to use these constants than the string version.

**Comment by mycFelix** [comment]
@kramasamy @maosongfu @billonahill - I'll send PR for this. And `UnsupportedEncodingException` doesn't need to be captured if we use `StandardCharsets.UTF_8`

**Comment by mycFelix** [comment]
merged #1607 and closed

**Comment by dwy189** [comment]
Why shall we Replace `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8`?

**Comment by billonahill** [comment]
It's more strongly typed and has compile time checks built in.
