### ISSUE TITLE
Does heron support CentOS 5

### ISSUE THREAD

**Issue by anty** [twitter/heron#1600]
Does heron currently only support Centos7?  I can't succesfully build heron on centos 5

**Comment by anty** [comment]
I follow the instructions on [Building on Linux Platforms
](http://twitter.github.io/heron/docs/developers/compiling/linux/#building-on-centos-7), but can't make success. 

>  bazel build --config=centos --verbose_failures heron/...
> INFO: Found 434 targets...
> ERROR: Process exited with status 1.
> INFO: Elapsed time: 3.080s, Critical Path: 2.92s

**Comment by anty** [comment]
Sometimes, it will fail with following error

>  # //third_party/python/pylint:pylint [action 'PexPython third_party/python/pylint/pylint.pex [for host]']
> (cd /root/.cache/bazel/_bazel_root/6f84414296ba6593093f156bd47eea3c/execroot/heron-0.14.5 && \
>   exec env - \
>   bazel-out/host/bin/third_party/pex/_pex --disable-cache --entry-point third_party.python.pylint.main bazel-out/host/bin/third_party/python/pylint/pylint.pex bazel-out/host/bin/third_party/python/pylint/pylint.pex.manifest)
> ERROR: Process exited with status 1.

**Comment by objmagic** [comment]
It should be fine to build on CentOS 5.

1. Could you please give us output of `./bazel_configure.py`?
2. The above error message has no useful information (weird even with ``--verbose_failures``). It would be good if we have more logs

**Comment by anty** [comment]
Hi objmagic, this is output for `./bazel_configure.py`

`Platform Linux
Using C compiler          :     /data/anty/testbed/gcc-build-5.1.0/bin/gcc (5.1.0)
Using C++ compiler        :     /data/anty/testbed/gcc-build-5.1.0/bin/g++ (5.1.0)
Using C preprocessor      :     /data/anty/testbed/gcc-build-5.1.0/bin/cpp (5.1.0)
Using C++ preprocessor    :     /data/anty/testbed/gcc-build-5.1.0/bin/cpp (5.1.0)
Using linker              :     /usr/bin/ld
Using Automake            :     /usr/bin/automake (1.11.1)
Using Autoconf            :     /usr/local/bin/autoconf (2.69)
Using Make                :     /usr/bin/make (3.81)
Using CMake               :     /usr/local/bin/cmake (2.8.12.2)
Using Python2             :     /data/anty/testbed/python/bin/python2.7 (2.7.12)
Using archiver            :     /usr/bin/ar
Using coverage tool       :     /data/anty/testbed/gcc-build-5.1.0/bin/gcov
dwp                       :     not found, but ok
Using nm                  :     /usr/bin/nm
Using objcopy             :     /usr/bin/objcopy
Using objdump             :     /usr/bin/objdump
Using strip               :     /usr/bin/strip
Wrote the environment exec file scripts/compile/env_exec.sh`

**Comment by anty** [comment]
Following is error output after add -s option to bazel
>
>>>>> # //third_party/java:yarn [action 'Building third_party/java/libyarn.jar (1 source file)']
(cd /root/.cache/bazel/_bazel_root/6f84414296ba6593093f156bd47eea3c/execroot/heron-0.14.5 && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/local-fastbuild/bin/third_party/java/libyarn.jar-2.params)
>>>>> # //third_party/python/pylint:pylint [action 'PexPython third_party/python/pylint/pylint.pex [for host]']
(cd /root/.cache/bazel/_bazel_root/6f84414296ba6593093f156bd47eea3c/execroot/heron-0.14.5 && \
  exec env - \
  bazel-out/host/bin/third_party/pex/_pex --disable-cache --entry-point third_party.python.pylint.main bazel-out/host/bin/third_party/python/pylint/pylint.pex bazel-out/host/bin/third_party/python/pylint/pylint.pex.manifest)
ERROR: Process exited with status 1.
INFO: Elapsed time: 0.220s, Critical Path: 0.12s
>

**Comment by anty** [comment]
I try to compile heron on Centos7, can't make any success anywhere.
1. this is the output of ` ./bazel_configure.py `
>
>Platform Linux
Using C compiler          :     /usr/bin/gcc (4.8.5)
Using C++ compiler        :     /usr/bin/g++ (4.8.5)
Using C preprocessor      :     /usr/bin/cpp (4.8.5)
Using C++ preprocessor    :     /usr/bin/cpp (4.8.5)
Using linker              :     /usr/bin/ld.bfd
Using Automake            :     /usr/bin/automake (1.13.4)
Using Autoconf            :     /usr/bin/autoconf (2.69)
Using Make                :     /usr/bin/make (3.82)
Using CMake               :     /usr/local/bin/cmake (3.3.2)
Using Python2             :     /usr/bin/python2.7 (2.7.5)
Using archiver            :     /usr/bin/ar
Using coverage tool       :     /usr/bin/gcov
Using dwp                 :     /usr/bin/dwp
Using nm                  :     /usr/bin/nm
Using objcopy             :     /usr/bin/objcopy
Using objdump             :     /usr/bin/objdump
Using strip               :     /usr/bin/strip
Wrote the environment exec file scripts/compile/env_exec.sh

**Comment by anty** [comment]
2. this is the error output
>
>
                 from src/logging_unittest.cc:33:
src/logging_unittest.cc: In function 'void TestLogging(bool)':
src/glog/logging.h:917:30: warning: typedef 'INVALID_REQUESTED_LOG_SEVERITY' locally defined but not used [-Wunused-local-typedefs]
                              INVALID_REQUESTED_LOG_SEVERITY);           \
                              ^
src/glog/logging.h:912:73: note: in definition of macro 'GOOGLE_GLOG_COMPILE_ASSERT'
   typedef google::glog_internal_namespace_::CompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                                                         ^
src/logging_unittest.cc:254:5: note: in expansion of macro 'LOG_EVERY_N'
     LOG_EVERY_N(ERROR, 4) << "Log every 4, iteration " << COUNTER << endl;
     ^
In file included from /usr/include/c++/4.8.2/ext/hash_set:60:0,
                 from src/glog/stl_logging.h:73,
                 from src/stl_logging_unittest.cc:53:
/usr/include/c++/4.8.2/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from src/utilities.h:73:0,
                 from src/googletest.h:38,
                 from src/stl_logging_unittest.cc:54:
src/base/mutex.h:137:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #   define _XOPEN_SOURCE 500  // may be needed to get the rwlock calls
 ^
In file included from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8.2/iostream:38,
                 from src/stl_logging_unittest.cc:34:
/usr/include/features.h:170:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
ERROR: Process exited with status 1.
INFO: Elapsed time: 197.198s, Critical Path: 192.43s

**Comment by kramasamy** [comment]
@anty - yes heron runs in centos5. It requires bazel to be compiled in centos5 and you need to ensure that the environment of compilers, make, cmake, etc confirms to version specified in the website http://heronstreaming.io. In fact, we run this in production.

**Comment by kramasamy** [comment]
@anty  - for centos7, please take a look at the docker file that we use at docker/Dockerfile.centos7 - it contains all the necessary commands and dependencies to run in centos7. hope this helps.
