### ISSUE TITLE
Delete c.t.h.spi.common.Jars

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1602]
This class is unused and should be removed. Also utility helpers should live in utils.

**Comment by mycFelix** [comment]
@billonahill - I'm not sure whether my understanding is correct. First the `c.t.h.spi.common.Jars` is unused in Heron project and it should be removed or deleted. Second, there are some utility helpers we may want to reserve, such as `getJars` ,`getClassPath`... which should be live in `utils` package. I'm not sure if creating a new Utils class named `JarsUtils` which contains `getJars` and `getClassPath` static method is what we want.

**Comment by billonahill** [comment]
AFAICT `Jars` is unused and without unit tests and hence should be deleted is what I'm proposing. I don't see a need to keep any of those unused methods around. Most of what it provides is also available in the guava `Files` class too I believe.

**Comment by mycFelix** [comment]
Understood

**Comment by objmagic** [comment]
close via #1620. Thanks.
