### ISSUE TITLE
heron-ui for bolts' execute latency and process latency are always 0

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#1640]
Check out the pic below, the execute latency and process latency for 10min, 1hr and 3hrs are 0s while the all time are not. There might be a bug in the UI

![image](https://cloud.githubusercontent.com/assets/16407807/21445182/b006d530-c86a-11e6-96ea-ae2cdc130755.png)

**Comment by objmagic** [comment]
prioritize this issue by adding it into milestone 0.14.6

**Comment by objmagic** [comment]
@nlu90 can you show me how to reproduce this?

**Comment by nlu90** [comment]
@objmagic you can look into our internal new heron-ui page to see the problem by selecting a topology, clicking one component and checking the metrics.

You may also try to reproduce it locally.

**Comment by objmagic** [comment]
@nlu90 

launched AckingTopology locally and didn't see any issue. Here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/3656079/22912402/01081bfa-f21a-11e6-9c52-e8a76b9c007e.png)
![image](https://cloud.githubusercontent.com/assets/3656079/22912416/09a9dde8-f21a-11e6-890b-b5d24e306409.png)

**Comment by objmagic** [comment]
delay this to 0.15.0
