### ISSUE TITLE
Code blocks for Yarn documentation are solid black

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1652]
The code blocks on this page are black:
http://twitter.github.io/heron/docs/operators/deployment/schedulers/yarn/

**Comment by objmagic** [comment]
resolved via https://github.com/twitter/heron/pull/1575 but this change was introduced after 0.14.5 so it was not included in the latest website build.

**Comment by billonahill** [comment]
When we fix large site bugs we should be able to easily republish the site
without waiting for the next release.

**Comment by objmagic** [comment]
I can push website change directly to `website` branch in the future.

**Comment by mycFelix** [comment]
@billonahill @objmagic - Please let me know after the release. I'll check the page again.

**Comment by objmagic** [comment]
@mycFelix fixed via #1652. Please check out http://twitter.github.io/heron/docs/operators/deployment/schedulers/yarn/

**Comment by mycFelix** [comment]
@objmagic - It's great! Thank you~
