### ISSUE TITLE
Improve log message for connection errors

### ISSUE THREAD

**Issue by congwang** [twitter/heron#1654]
Logging a number is confusing:
`W0103 20:25:17.030653 31955 stmgr-client.cpp:94] Could not connect to stmgr stmgr-147 running at <host>:<port> due to: 1`

**Comment by objmagic** [comment]
Not sure if important but please do not expose internal service hostname to the public

**Comment by kramasamy** [comment]
yes - please remove the host name,

**Comment by kramasamy** [comment]
thanks @objmagic for pointing it out. updated it.

**Comment by objmagic** [comment]
got paged this morning and confused by these unclear log messages again...
