### ISSUE TITLE
tmaster exits with GLIB errors after intalling on Centos

### ISSUE THREAD

**Issue by thomas4g** [twitter/heron#1659]
Error I see in `heron-executor-0.stdout`: 

```
01/11/2017 01:39:41 +0000:INFO: heron-tmaster stderr: ./heron-core/bin/heron-tmaster: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./heron-core/bin/heron-tmaster)
./heron-core/bin/heron-tmaster: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./heron-core/bin/heron-tmaster)
./heron-core/bin/heron-tmaster: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./heron-core/bin/heron-tmaster)
./heron-core/bin/heron-tmaster: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./heron-core/bin/heron-tmaster)
./heron-core/bin/heron-tmaster: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./heron-core/bin/heron-tmaster)
./heron-core/bin/heron-tmaster: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./heron-core/bin/heron-tmaster)
```

What I did to get there:

1. Downloaded & ran the `heron-client-install-0.14.5-centos.sh` and `heron-tools-install-0.14.5-centos.sh` scripts, installing into `/opt/heron`
2. Submitted my topology jar with: `heron submit local my-jar.jar com.my-org.MyTopo MyTopo`

System information:
centos-release-6-8.el6.centos.12.3.x86_64

Steps I attempted to remedy:
`sudo yum install libstdc++  glibc-devel`

Normally I would not report this as an "issue" with the software itself, but I am beginning to suspect something could be wrong with the installation script rather than with my system.

**Comment by objmagic** [comment]
we've seen similar issues when we were doing some internal experiments. will investigate.

cc @congwang

**Comment by thomas4g** [comment]
@objmagic okay, thanks. I noticed after filing this issue that the compilation instructions for Heron (which I hadn't looked at before since I was just installing with the script) mention it can only be compiled on CentOS 7. I'm on CentOS 6. Could that be the source of the issue?

**Comment by objmagic** [comment]
@thomas4g that is very possible. The dynamically linked libstdc++ on your machine probably doesn't have the version `heron-tmaster` requires.

**Comment by kramasamy** [comment]
Yes - we provide the binaries for only centos 7 only. If you want to run on centos 6, you need to compile and install. Please follow the instructions in the web page.

**Comment by thomas4g** [comment]
@kramasamy @objmagic OK, thanks very much.
