### ISSUE TITLE
Use resources instead of data to load sample files in Java tests

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1668]
See: https://groups.google.com/forum/#!topic/bazel-discuss/VUC8kTEXDYo

We also need to update the [java_tests.bzl](https://github.com/twitter/heron/blob/master/tools/rules/java_tests.bzl)

example: https://github.com/bazelbuild/bazel/blob/master/examples/java-native/src/main/java/com/example/myproject/Greeter.java#L36

**Comment by objmagic** [comment]
will be tackling this in https://github.com/twitter/heron/pull/1629

**Comment by objmagic** [comment]
#1629 implemented [an example](https://github.com/twitter/heron/pull/1629/files#diff-82363f3f748309fe4666863b76fca86fR57), but we still needs to [specify some extra paths](https://github.com/twitter/heron/pull/1629/files#diff-6180a9cda3c7dbfa9b29da4b6b4a7f0eR67) to the resource. Google's Bazel example looks simpler. We need to investigate why, and change to use `resource` for all BUILD files.

**Comment by objmagic** [comment]
seems we have done this before for `java_library`: https://github.com/twitter/heron/blob/master/heron/spi/src/java/com/twitter/heron/spi/common/Resource.java

**Comment by billonahill** [comment]
com/twitter/heron/spi/common/Resource.java is unrelated. That's a heron object to model a container or instance resource (i.e., ram, cpu, disk).

**Comment by billonahill** [comment]
Oh yes, sorry. I forgot about this class. We also have a Resources class, which I was talking about. Too much overloading...
