### ISSUE TITLE
Add a metric to indicate average queue length in #packets pending between stmgr and each instance

### ISSUE THREAD

**Issue by avflor** [twitter/heron#1671]
This metric can be useful to detect overloaded instances.

**Comment by congwang** [comment]
@avflor By number of tuples, does it count all kinds of tuples? Ack tuples, fail tuples too?

**Comment by avflor** [comment]
@congwang Just the number of data tuples (no ack tuples). What is fail tuples? If they have failed would they be in the queue?

**Comment by maosongfu** [comment]
We have 3 metrics: # of data_tuple, ack_tuple and fail_tuple?

**Comment by avflor** [comment]
That would be great! We might need these metrics in the future.

**Comment by maosongfu** [comment]
Pull request is here: #1695

**Comment by objmagic** [comment]
resolved via https://github.com/twitter/heron/pull/1695
