### ISSUE TITLE
0.14.5 libraries not published?

### ISSUE THREAD

**Issue by dmarchand** [twitter/heron#1684]
Can't seem to locate com.twitter.{heron-kafka,heron-storm,heron-api,heron-spi}-0.14.5 on Maven Central or the Twitter Maven cache.

Is this intentionally not published yet?

**Comment by objmagic** [comment]
@dmarchand I believe this is our mistake. 

@billonahill I will update the OSS release process both internally and on GitHub.

@kramasamy Can you publish 0.14.5 to Maven?

**Comment by kramasamy** [comment]
@dmarchand - the library is published and pushed to maven. Please check and close the issue accordingly.

**Comment by dmarchand** [comment]
Confirmed libs are now available.
