### ISSUE TITLE
redundant rule `heron/config/src/yaml:conf-yaml`

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1723]
https://github.com/twitter/heron/blob/master/heron/config/src/yaml/BUILD#L12 matches nothing

**Comment by objmagic** [comment]
any idea? @billonahill @kramasamy

**Comment by billonahill** [comment]
It looks unused and not necessary to me. Also, targets like this in that `BUILD` file are misnamed IMO, since they catch all configs, not just yaml:

```
filegroup(
    name = "conf-aurora-yaml",
    srcs = glob(["conf/aurora/*"]),
)
```

**Comment by objmagic** [comment]
will remove. and rename.
