### ISSUE TITLE
packing algorithm class is included in scheduler files

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1724]
https://github.com/twitter/heron/blob/master/tools/rules/heron_client.bzl#L30 which is a duplicate of https://github.com/twitter/heron/blob/master/tools/rules/heron_client.bzl#L43. That said, `lib/scheduler` will have two jar about packing algos. Any idea why? @billonahill

**Comment by objmagic** [comment]
why include heron-core (heron-dist) inside of client? internal build rule does not include it in client package https://github.com/twitter/heron/blob/master/scripts/packages/BUILD#L254

**Comment by billonahill** [comment]
I don't know why the packing files are duplicated in `heron_client.bzl` but this seems incorrect to me.

**Comment by kramasamy** [comment]
Heron client includes core for running local cluster.

**Comment by objmagic** [comment]
@kramasamy Good to know. Thanks!
