### ISSUE TITLE
Submit failure when packing plan numContains different from configured numContainers

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1742]
`IPacking` algorithms might ignore the configured instance/container resource settings or the configured number of containers. `RoundRobinPacking` ignores the former, `ResourceCompliantRRPacking` ignores the later.

Currently if the packing plan calls for a different number of containers than what was configured, and exception is throw upon submit. Instead we should log a warning and update the configs to match the packing plan. (Even better would be to leave the configs and update the framework to look exclusively at the packing plan, but that's a larger effort.)

**Comment by maosongfu** [comment]
Agree that "leave the configs and update the framework to look exclusively at the packing plan, but that's a larger effort" is the best solution.

**Comment by billonahill** [comment]
Yeah, the other problem with that solution though, is that it's error prone, in that anyone downstream could look at the config or the topology for the number of containers and use that, which would be incorrect. I also suspect there are places where the config is accessible but not the packing plan. I don't love the current solution but I think it's safest and most consistent.
