### ISSUE TITLE
parameter type not consistent in com.twitter.heron.api.Config

### ISSUE THREAD

**Issue by leonardgithub** [twitter/heron#1747]
version: 0.14.5

1. I get the heron-api:0.14.5 by maven as below, but the error "incompatible types: ByteAmount cannot be converted to long" occurs
`<dependency>
    <groupId>com.twitter.heron</groupId>
    <artifactId>heron-api</artifactId>
    <version>0.14.5</version>
</dependency>`

2. Then I check the source code in the downloaded heron-api jar, it is:
    public void setContainerDiskRequested(long var1) {
        setContainerDiskRequested(this, var1);
    }

3. But the type is ByteAmount in github
https://github.com/twitter/heron/blob/master/heron/api/src/java/com/twitter/heron/api/Config.java#L412
  public void setContainerDiskRequested(ByteAmount nbytes) {
    setContainerDiskRequested(this, nbytes);
  }

I see the the latest release version is 0.14.5, is there something wrong?

**Comment by billonahill** [comment]
What you show in 3. is the head of master, where that value is now `ByteAmount`. You can see in the 0.14.5 tagged version that it was a long at the time of the release: https://github.com/twitter/heron/blob/0.14.5/heron/api/src/java/com/twitter/heron/api/Config.java

Can you provide a test case that can be used to reproduce what's described in 1? Does the same thing happen when using a build made from the head?

**Comment by leonardgithub** [comment]
@billonahill

**Comment by objmagic** [comment]
cc @nlu90, who is handling similar issues now

**Comment by leonardgithub** [comment]
@billonahill It is OK now by using 
https://github.com/twitter/heron/blob/0.14.5/heron/examples/src/java/com/twitter/heron/examples/ExclamationTopology.java.
