### ISSUE TITLE
[RFC] Evolving tracker API endpoint ``/topologies/executionstate''

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1754]
After discussion with @billonahill and @maosongfu about #1734, we think it is a good idea to evolve the tracker API endpoint ``/topologies/executionstate``.  Here is the JSON result of the API call:
```json
{
    "executiontime": 0.00013208389282226562,
    "message": "",
    "result": {
        "cluster": "wee",
        "environ": "devel",
        "has_physical_plan": true,
        "has_scheduler_location": true,
        "has_tmaster_location": true,
        "jobname": "tracker-API-examples",
        "release_tag": "",
        "release_username": "r",
        "release_version": "master",
        "role": "r",
        "submission_time": 1488913433,
        "submission_user": "r"
    },
    "status": "success",
    "version": "0.14.5"
}
```

Most these fields are static data, except "has_xxx", which may look like runtime info. In #1734, we are adding stmgrs registration summary, which is definitely runtime info. We think it's time to split `/topologies/executionstate` and add new endpoints to better reflect the API result. For example, `topologies/metadata`, `topologies/runtimeinfo`...

Comments are welcomed.

This involves API change which may affect UI but it should be very easy for us to coordinate the changes.

**Comment by billonahill** [comment]
+1

As discussed I think we should add the following api endpoints:

`/topologies/metadata` - existing static topology info from `/topologies/executionstate`. Possible additional future data like git sha, build date, etc.
`/topologies/runtimestate` - state information about the topology. Stream manager registration state and any `has_foo` states from `/topologies/executionstate` that are actually in use an necessary.

We could add the new API endpoints and then change the UI to use them, then remove executionstate.

**Comment by huijunw** [comment]
what is difference between existing "/topologies/info" and new "/topologies/metadata" ?

**Comment by objmagic** [comment]
@huijunw ``info`` is really an aggregation of all the informations.

**Comment by billonahill** [comment]
@objmagic would you please provide a proposal with an overview of the current relevant enpoints, along with the the new proposed endpoints, both with example data. Info, seems like it can also be related to this effort, but it's generically named to not convey it's purpose.

**Comment by objmagic** [comment]
@billonahill 

Current API endpoint `topologies/executionstate` gives you
```
{
  status: "Running",
  release_username: "rli",
  has_tmaster_location: true,
  jobname: "EX",
  release_version: "rli/tm-stmgr-registration",
  submission_user: "rli",
  submission_time: 1489523952,
  viz: "",
  has_scheduler_location: true,
  has_physical_plan: true,
  cluster: "local",
  release_tag: "",
  environ: "default",
  role: "rli"
}
```

We should split API endpoint `topologies/executionstate` into two endpoints:
* `topologies/metadata`:
```
{
  release_version: "rli/tm-stmgr-registration",
  cluster: "local",
  release_tag: "",
  environ: "default",
  submission_user: "rli",
  release_username: "rli",
  submission_time: 1489523952,
  viz: "",
  role: "rli",
  jobname: "EX"
}
```
* `topologies/runtimestate`
```
{
  has_tmaster_location: true,
  stmgrs_reg_summary: {
    registered_stmgrs: [
      "stmgr-1",
      "stmgr-2"
    ],
    absent_stmgrs: [ ]
  },
  has_scheduler_location: true,
  has_physical_plan: true
}
```

In `topologies/runtimestate`, we add `stmgrs_reg_summary` (to @billonahill I will change it to OO style later)

As for `topologies/info`, it is an aggregation of all the infos
```
 {
  name: "EX",
  tmaster_location: ...
  physical_plan: ...
  runtime_state: ...
  scheduler_location: ...
  logical_plan: ...
  execution_state: ...
  id: "EX26810c0f-c992-4962-b01a-4c482609f8f8",
  metadata: {}
}
```

**Comment by billonahill** [comment]
Right, info is a collection of everything.

For `runtimestate` if we structure like this, we can be more extensible to serve additional info later:
```
stmgrs {
  "stmgr-1": { "is_registered": True }
  "stmgr-2": { "is_registered": False }
}
```

**Comment by objmagic** [comment]
Updated view of result of `topologies/runtimestate`

```
{
  has_tmaster_location: true,
  stmgrs: {
    stmgr-1: {
      is_registered: true
    },
    stmgr-2: {
      is_registered: true
    }
  },
  has_scheduler_location: true,
  has_physical_plan: true
}
```
