### ISSUE TITLE
Fix OneSpoutMultiTasks test

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1757]
related to #1691

**Comment by congwang** [comment]
What's the status of this issue? I saw it twice this week:

`20170321183034_IntegrationTest_OneSpoutBoltMultiTasks_98f78c1a-21eb-42f1-8116-b0b65f47c1e8`

**Comment by objmagic** [comment]
I got other tasks to do. Can you PR to temporarily disable it? See https://github.com/twitter/heron/pull/1700

**Comment by objmagic** [comment]
i will look into it when I finish other tasks
