### ISSUE TITLE
topology definition temp directory not specified

### ISSUE THREAD

**Issue by leonardgithub** [twitter/heron#1760]
When I run heron/heron/examples/src/java/com/twitter/heron/examples/MultiSpoutExclamationTopology.java, the error shows as below:
Exception in thread "main" java.lang.RuntimeException: topology definition temp directory not specified
	at com.twitter.heron.api.HeronSubmitter.submitTopology(HeronSubmitter.java:76)
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:60)
	at com.twitter.heron.examples.MultiStageAckingTopology.main(MultiStageAckingTopology.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

Any solution?

**Comment by billonahill** [comment]
Would you please provide steps to reproduce.

**Comment by maosongfu** [comment]
It is likely having a version mismatch between heron-cli topology building against with and the heron-cli to submit topology. Could you check it?

**Comment by congwang** [comment]
The last time I saw this it was a version mismatch, I changed the version in maven file and recompile the topology code.

**Comment by leonardgithub** [comment]
IDE: Intellij Idea
steps: 
1. create an new java maven project
2. add the below into pom.xml
` <dependency>
            <groupId>com.twitter.heron</groupId>
            <artifactId>heron-storm</artifactId>
            <version>0.14.5</version>
        </dependency>
        <dependency>
            <groupId>com.twitter.heron</groupId>
            <artifactId>heron-api</artifactId>
            <version>0.14.5</version>
        </dependency>
        <dependency>
            <groupId>com.twitter.heron</groupId>
            <artifactId>heron-kafka</artifactId>
            <version>0.14.5</version>
        </dependency>
        <dependency>
            <groupId>com.twitter.heron</groupId>
            <artifactId>heron-spi</artifactId>
            <version>0.14.5</version>
        </dependency>`

3. copy the example folder into the project
4. run the main method MultiSpoutExclamationTopology
5. "topology definition temp directory not specified" is shown

**Comment by billonahill** [comment]
What is the command you're using in step 4 and what's the classpath? As pointed out above, you probably have a different Heron client binary being used than the version the topology was built against. Typically you would want to also install the heron client locally and submit a topology that way, which will assure you that you're running the client version you expect.

**Comment by leonardgithub** [comment]
@billonahill Thank you for your answers.
in step 4, I just right click the MultiSpoutExclamationTopology.java at Intellij Idea, then run the main method.

The heron info at my local environment is:
leonard@leonard-PC:~$ heron version
heron.build.version : '0.14.5'
heron.build.time : Fri Nov 18 09:38:42 PST 2016
heron.build.timestamp : 1479490745000
heron.build.host : tw-mbp-kramasamy
heron.build.user : kramasamy
heron.build.git.revision : 89fbce68156464621aaf00646921de0770cd2b59
heron.build.git.status : Clean
leonard@leonard-PC:~$ 
leonard@leonard-PC:~$ echo $CLASSPATH
/usr/java/default/lib/dt.jar:/usr/java/default/lib/tools.jar

**Comment by billonahill** [comment]
That approach to running a topology (invoking topology main directly) has not been tested AFAIK. The heron client sets a number of environment values and passes parameters to main, so you'd need to mimic the client interaction if you want to run the main directly. I recommend reading the client code at tools/client/src/python to see how you could mimic the client behavior in this way, or just run the topology using the heron client. You could also try using heron Simulator, which is intended to allow a topology to be run in a single jvm in an IDE.

http://twitter.github.io/heron/docs/developers/simulator-mode/

**Comment by leonardgithub** [comment]
@billonahill I will try, thanks for your help

**Comment by leonardgithub** [comment]
@objmagic HI, could you tell me how to use mailling list, I find a mvn repository problem just now.
see http://mvnrepository.com/artifact/com.twitter.heron/heron-kafka/0.14.5, could not find artifact com.twitter.heron:heron-api:jar:SNAPSHOT

**Comment by objmagic** [comment]
@leonardgithub Mailing list is at https://groups.google.com/forum/#!forum/heron-users

@kramasamy Can you have a look the Maven Jar issue @leonardgithub mentioned above?

**Comment by kramasamy** [comment]
@leonardgithub - I went to mvn website and able to download the jar. What is the specific issue that you are seeing?

**Comment by leonardgithub** [comment]
HI @kramasamy 
http://central.maven.org/maven2/com/twitter/heron/heron-kafka/0.14.5/heron-kafka-0.14.5.pom
`<dependency>
<groupId>com.twitter.heron</groupId>
<artifactId>heron-api</artifactId>
<version>SNAPSHOT</version>
<scope>compile</scope>
</dependency>`

Should it be 0.14.5?

**Comment by lewiskan** [comment]
Hi @leonardgithub - thanks for pointing this out, and you're right SNAPSHOT should be replaced by 0.14.5.  It usually is updated in the MVN pom file, but this must have been missed.  We will upload a new .jar soon, thanks for catching this.

**Comment by lewiskan** [comment]
done, new version uploaded for 0.14.5, thanks.

**Comment by leonardgithub** [comment]
@lewiskan Thank you very moch

**Comment by leonardgithub** [comment]
@lewiskan I use the aliyun as a maven repository mirror, but the heron-api and heron-storm is still SNAPSHOT in http://maven.aliyun.com/nexus/service/local/repositories/central/content/com/twitter/heron/heron-kafka/0.14.5/heron-kafka-0.14.5.pom, any sulotion?
