### ISSUE TITLE
heron submit: error: unrecognized arguments: ExclamationTopology

### ISSUE THREAD

**Issue by pingzh** [twitter/heron#1825]
I have installed heron in the mac and try to following the tutorial https://twitter.github.io/heron/docs/getting-started/ , but I am getting this error:
```
$ heron submit local ~/.heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology --deploy-deactivated
usage: heron submit [options] cluster/[role]/[env] topology-file-name topology-class-name [topology-args]
heron submit: error: unrecognized arguments: ExclamationTopology
```

```
$ heron version
heron.build.version : '0.14.6'
heron.build.time : Thu Mar 9 23:28:03 PST 2017
heron.build.timestamp : 1489130892000
heron.build.host : tw-mbp-kramasamy
heron.build.user : kramasamy
heron.build.git.revision : 5da5be68af918438811f903bde208577db6e3517
heron.build.git.status : Clean
```

Could someone please take a look?

**Comment by objmagic** [comment]
@pingzh If you are following the tutorial, you should have downloaded [heron-client-install-0.14.7-darwin.sh](https://github.com/twitter/heron/releases/download/0.14.7/heron-client-install-0.14.7-darwin.sh). Why `heron version` is still at 0.14.6? 

Anyway, I installed this script on my machine and your command works for me.

**Comment by pingzh** [comment]
Thanks for replying.
hmm, 0.14.7 was just released. I have uninstalled the old one and reinstalled 0.14.7. It still does not work :( and got the same error.

btw, there is no 
`heron-tools-install-0.14.7-darwin.sh``` in the download page.

**Comment by objmagic** [comment]
@pingzh 

Can you run again with ``--verbose``?

Also, ``heron-tools-install-0.14.7-darwin.sh`` is available now.

**Comment by pingzh** [comment]
@objmagic thanks. I have installed `heron-tools-install-0.14.7-darwin.sh` and here is the output:

```
~/Desktop
$  heron submit local ~/.heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology --deploy-deactivated --verbose
usage: heron submit [options] cluster/[role]/[env] topology-file-name topology-class-name [topology-args]
heron submit: error: unrecognized arguments: ExclamationTopology
~/Desktop
$
```

**Comment by objmagic** [comment]
@pingzh what is `heron version`? Is it 0.14.7 now?

**Comment by pingzh** [comment]
yep

```
$ heron version
heron.build.version : '0.14.7'
heron.build.time : Thu Apr 27 14:50:04 PDT 2017
heron.build.timestamp : 1493329804000
heron.build.host : tw-172-24-220-90.office.twttr.net
heron.build.user : mobile
heron.build.git.revision : 052dd4d25d3c64a73d8751d346a4dad7ccdab2b2
heron.build.git.status : Modified
```

**Comment by objmagic** [comment]
I cannot reproduce so I cannot answer your question.

**Comment by pingzh** [comment]
@objmagic, still, thanks for your help.

**Comment by objmagic** [comment]
cannot reproduce so close for now
