### ISSUE TITLE
New topologies should appear first on heron-ui page

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1826]

**Comment by maosongfu** [comment]
Can you explain more about this issue? For instance, background, current status, goal and the justification.

**Comment by nlu90** [comment]
Any concrete examples?

**Comment by objmagic** [comment]
currently topologies are sorted by names when you open heron-ui. When user submits his topology, it would be better if he sees his topology at the very top of the ui list.

**Comment by billonahill** [comment]
Having the sort be based on submit time is helpful for someone who just submitted a job, but not for others. If we want this, we should consider letting the user change the sort order (submit time asc/desc, alpha, etc).

**Comment by objmagic** [comment]
@billonahill 

> but not for others

I will assume "others" mean people who open heron-ui but did not submit a new job. In this case, nothing has changed: he still has to use search bar or scroll up and down to find his job. I think in most cases, people open heron-ui because they just submitted a job.

Can you give me an example of sorting topology by submission time by default being not helpful to a particular group of users? What particular benefits do we have from sorting topology by names?

**Comment by kramasamy** [comment]
sort by each field is good enough and we have powerful search as well.

**Comment by objmagic** [comment]
ok then
