### ISSUE TITLE
AuroraScheduler doesn't request max container memory correctly

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#1835]
In the code,

https://github.com/twitter/heron/blob/master/heron/schedulers/src/java/com/twitter/heron/scheduler/aurora/AuroraScheduler.java#L96

when creating `containerResource`, we should use `updatedPackingPlan` instead of the `packing`. 

`updatedPackingPlan` aligns containers' memory to the max one required among all containers while `packing` only contains the memory requirement to run all instance in that container.

**Comment by objmagic** [comment]
closed via #1836

**Comment by nlu90** [comment]
#1850
