### ISSUE TITLE
SCP uploader variable

### ISSUE THREAD

**Issue by Laxman-SM** [twitter/heron#1853]
i am having uploader configuration as per below mention document link
https://github.com/twitter/heron/blob/master/website/content/docs/operators/deployment/uploaders/scp.md

## **### Example SCP Uploader Configuration**

heron.uploader.ssh.command.connection:   "user@xx.xxx.xx.xx"

heron.aurora
1
fetch_user_package = Process(
  name = 'fetch_user_package',
  cmdline = 'scp -i ~/.ssh/id_rsa user@xx.xxx.xx.xx:%s %s && tar zxf %s' % (heron_topology_jar_uri, \
      topology_package_file, topology_package_file)
)

### output during the topology submission:

[2017-05-11 10:36:01 +0000] [INFO] com.twitter.heron.spi.utils.ShellUtils: Running synced process: ``ssh -i /home/ubuntu/.ssh/sit.pem ubuntu@xx.xxx.xx.xx mkdir -p /home/ubuntu/.herondata/repository/topologies/aurora/ubuntu/APITopology'' 

how the variable substitution work here. this upload binay on mentioned node and directory. 
how the other node communicate for binary download. 
today my scp node goes down and all topology submission stop working. so replace node ip in heron.aurora. after that topology submission start working.

this command uploading topology.tar.gz to /home/ubuntu/.herondata/repository/topologies/aurora/ubuntu/APITopology/ directory

i am still got confused /understand how binary download  working on slave node.

**Comment by Laxman-SM** [comment]
also 
declare -a hosts=(ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com ec2-xx.xxx.xx.xx.compute-1.amazonaws.com ec2-xx-xxx-xx-xx.compute-1.amazonaws.com)

how to replace custom variable on scp -i ~/.ssh/id_rsa user@xx.xxx.xx.xx:%s x.xxx.xx.xx place.

**Comment by billonahill** [comment]
The scp node needs to be available to all other nodes. The client uploads to it and all nodes download from it. If its going down, you will run into problems with this approach.

Please use the mailing list for questions instead of opening tickets. Closing this. Please continue the discussion on the list if you have additional questions.
