### ISSUE TITLE
heron tmaster doesn't watch the tmaster location

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#1869]
Heron UI page indicates some topologies are not running correctly. After some investigation, we found that the tmaster locations in zk statemgr are missing for all these topologies.

The facts we know are:
1. the tmaster location node in zk is an ephemeral node
2. there's no code deleting the tmaster location from zk
3. once a tmaster is restarted, it registeres its location to zk

The suspicion is that there's some network issue between tmaster and zk. This causes the zk to delete the tmaster locaiton node while tmaster keeps running without register itself again. All the stmgrs notice this event and try to fetch a new tmaster location but keep failing.

**Comment by billonahill** [comment]
The red font is also problematic because it's a visual cue without any indicator to what exactly. Nobody knows what red means.

**Comment by maosongfu** [comment]
According to: https://github.com/twitter/heron/blob/master/heron/tools/ui/resources/static/js/alltopologies.js#L21

The red font means: the tmaster_location does not exist in zookeeper
The orange font means: the physical_plan does not exist in zookeeper

**Comment by nlu90** [comment]
After some investigation, we found that the UI is showing the status correctly. For all these topologies, the tmaster locations are missing.

Now the question is why those tmaster locations disappear from the zk statemgr. The facts we have are:
1. the tmaster location node in zk is an ephemeral node
2. there's no logic in the code that delete the tmaster location from zk
3. once a tmaster restarted, it will registered its location to zk

The current suspicion is that there's network problem between the tmaster and zk. It causes the zk think the seesion is closed thus delete the tmaster locaiton. But in the meantime, the tmaster is running fine.

**Comment by billonahill** [comment]
@maosongfu thanks for solving that mystery. Unfortunately users of the UI don't know what the scheme is and if they did, it still wouldn't really be actionable to them.

**Comment by maosongfu** [comment]
@billonahill +1.

**Comment by srkukarni** [comment]
@nlu90 local file system state manager does not support watches, so thats probably not the right method to reproduce this. Try localzk instead.

**Comment by nlu90** [comment]
@srkukarni I submitted the topology to production aurora cluster

**Comment by nlu90** [comment]
#1872
