### ISSUE TITLE
IRichSpout No class def found when deployting

### ISSUE THREAD

**Issue by jrpspam** [twitter/heron#1907]
my first heron attempt builds in mvn but when I try to deploy via (heron submit local ~/cnam-heron-workspace/cnam/target/cnam-1.0-SNAPSHOT.jar biz.neustar.cnamheron.CnamTopology CnamTopology) my spout which extends BaseRichSpout throws 

Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/topology/IRichSpout.

I pulled the examples/AckingTopology.java fromgithub and made a mvn project for it similar to above, but it also builds (mvn clean install) just fine but throws same runtime exception.

my MVN POM file is pretty basic: (below). I've added 0.14.6 because I can't locate 0.14.7, but I believe it should be OK

   
    <dependency>
          <groupId>com.twitter.heron</groupId>
          <artifactId>heron-storm</artifactId>
          <version>0.14.6</version>
    </dependency>

As for contents of my actual jar:

0 Fri May 26 18:25:34 UTC 2017 META-INF/
   126 Fri May 26 18:25:32 UTC 2017 META-INF/MANIFEST.MF
     0 Fri May 26 18:25:32 UTC 2017 biz/
     0 Fri May 26 18:25:32 UTC 2017 biz/neustar/
     0 Fri May 26 18:25:32 UTC 2017 biz/neustar/cnamheron/
  2427 Fri May 26 18:25:32 UTC 2017 biz/neustar/cnamheron/CnamTopology$CnamQuerySpout.class
  2087 Fri May 26 18:25:32 UTC 2017 biz/neustar/cnamheron/CnamTopology.class
  2130 Fri May 26 18:25:32 UTC 2017 biz/neustar/cnamheron/CnamTopology$TriageBolt.class
     0 Fri May 26 18:25:34 UTC 2017 META-INF/maven/
     0 Fri May 26 18:25:34 UTC 2017 META-INF/maven/com.neustar/
     0 Fri May 26 18:25:34 UTC 2017 META-INF/maven/com.neustar/cnam/
   882 Fri May 26 17:14:24 UTC 2017 META-INF/maven/com.neustar/cnam/pom.xml
   107 Fri May 26 18:25:32 UTC 2017 META-INF/maven/com.neustar/cnam/pom.properties

Any help appreciated. Thanks

**Comment by nlu90** [comment]
@jrpspam the `NoClassDefFoundError ` is caused by the IRichSpout file available at compile time but missing at runtime. I would suggest you to check the correct mvn command to build a deployment jar with all the classes packaged.

**Comment by jrpspam** [comment]
Thanks, sorry to be dense but the whole "plugin" concept is not clear. If I want to create a simple heron project w/ spout/bolts and I want to be able to use 'heron submit' on the jar produced and I have specified the heron dependency as noted above in my POM, what mvn package/install build options do I need? Where does plugin fit in this picture? Is there not some basic example of how to take a simple heron example -- ExclamationTopology -- and build/package/install it based on the java source and be able to deploy it via 'heron submit'? I do not see what mvn command is relevent in this simple scenario. Thanks very much for any clues.

**Comment by jrpspam** [comment]
Okay,, found example of how to do it. Building jar w/ dependencies takes a lot of pom.xml to get working. Absolutely nothing obvious about how to do it. Might be very nice if the heron examples came w/ an actual working pom.xml that one could use as a starting point. I had to add entire build section to pom as below:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.neustar</groupId>
  <artifactId>cnam</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>cnam</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    
    
    <dependency>
          <groupId>com.twitter.heron</groupId>
          <artifactId>heron-storm</artifactId>
          <version>0.14.6</version>
    </dependency>  
  </dependencies>
  
    <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.0</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
	  <plugin>
	    <groupId>org.codehaus.mojo</groupId>
	    <artifactId>exec-maven-plugin</artifactId>
	    <version>1.2.1</version>
	    <configuration>
	      <mainClass>com.twitter.storm.Topology</mainClass>
	  	  <classpathScope>compile</classpathScope>
	    </configuration>
	  </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>biz.neustar.cnamheron.CnamTopology</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>

**Comment by kramasamy** [comment]
Please take a look at following repo

www.github.com/kramasamy/heron-starter

Cheers
/karthik
