### ISSUE TITLE
Possible race condition during Heron update

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1932]
During the Heron update command the following flow is orchestrated by the scheduler:

1. scheduler: deactivate
  a. tmaster: deactivated
1. scheduler: delete physical plan
1. scheduler: update packing plan in state manager
  a. executors: detects new packing plan
  b. executor0: refreshes process list, restarts TMaster
    1. tmaster: restarts with new packing plan
    1. tmaster: receive new strmgr registrations
    1. tmaster: satisfies new packing plan
    1. tmaster: creates/distributes new physical plan
1. scheduler: await new physical plan
1. scheduler: receive new physical plan
1. scheduler: activate
  a. tmaster: activated

The scheduler deletes the physical plan so that the TMaster will restart with a new packing plan, recognize stream manager registration requests and build a new physical plan representing the new packing plan.

Since the executors all refresh their packing plans in parallel, a potential race condition exists if executor0 takes a long time to restart the TMaster (i.e. step 3b) (this happened due to a python issue fixed by #1930).

In this case new stream managers will register themselves with the old TMaster. The TMaster will generate a new physical plan that matches of old packing plan (if it can) and update it in the state manager. The scheduler will detect the new packing plan and complete the update, but the topology will still be in the old packing plan state (new scale-out stream managers will go unrecognized). Finally the TMaster will get restarted by the executor with new packing plan. It will load the old physical plan and reject registration requests by the new stream managers.

What is needed is a guarenteed way for the scheduler to invalidate/update the packing plan on the TMaster that doesn't rely on an asynchronous change propagating through the stream manager.

**Comment by billonahill** [comment]
Paired with @maosongfu and @nlu90 regarding the fix for this.

If we change TMaster to take a ZK watch on the packingplan node, it can update it internally immediately when it changes and then build a new physical plan to match it. That would negate the need for the scheduler to delete the physical plan and for executor0 to restart the TMaster. It also separates concerns better in that the scheduler controls the lifecycle of the packing plan and the TMaster controls the lifecycle of the physical plan.

**Comment by billonahill** [comment]
I've got a full patch to handle the described logic on branch `billg/tmaster_packing`. Will break it up into smaller PRs for review.
https://github.com/twitter/heron/compare/billg/tmaster_packing?expand=1

**Comment by huijunw** [comment]
why not let scheduler and tmaster talk directly rather than use packing plan in statemgr in between as communication signal ?

**Comment by billonahill** [comment]
It won't double it since TMaster only runs on 1 node, so it would add 1:1 with the number of topologies we run, which is insignificant.

We use a watch on statemanger for the packing plan for a couple of reasons:
- The executors need the packing plan and doing RPC with them isn't practical due to their lifecycle. Following the same patter for the TMaster is consistent.
- The initial deployment should be able to proceed without a requirement that the deploying user (where the scheduler-as-a-library might run) maintains a connection to the topology for the entire startup phase. So the client puts some state in statemanager and if that succeeds it launches the aurora containers and it's done. From then on the topology can initialize itself. We don't want the production topology to have a dep on the users client, which scheduler<->tmaster RPC would require.
