### ISSUE TITLE
duplicate active stmgrs due to zombie container

### ISSUE THREAD

**Issue by huijunw** [twitter/heron#2079]
Zombie container:
- The Aurora thought the container X was dead.
- The connections between the container X and some other containers are lost, but the connection between X and Tmaster exists.
- The processes are still running inside the container X.
- Aurora starts a new container Y for the zombie container X.
- Two stmgrs X and Y are now sending heartbeat to the Tmaster.

The present behavior of Tmaster:
Tmaster rejects the new stmgr Y registration and waits for the old stmgr X to timeout. However, we find that the zombie container X does not stop for long time.

Aurora is supposed to assure no duplicate containers, however this assumption is not always truth. A proposal on Heron side:
When Tmaster finds two duplicate stmgrs X and Y, Tmaster sends _killcontainer_ to both X and Y. The container X exits and Aurora does not restart it. The container Y exits and Aurora restarts it. In the end, only one container Y survives.
@billonahill @srkukarni @kramasamy comments are welcome.

**Comment by srkukarni** [comment]
Could you elaborate more on how/who the Tmaster would send the 'killcontainer' message? Is it to the stmgrs in X and Y. Or to the scheduler somehow?

**Comment by huijunw** [comment]
There is a handler in heron-shell, which can make heron-executor suicide. 
https://github.com/twitter/heron/blob/master/heron/shell/src/python/main.py#L37

Tmaster may send request to this heron-shell handler

**Comment by nlu90** [comment]
The assumption here is once the executor in zombie host's container X is killed, it will not be restarted by Aurora again. But the executor in normal host's container Y is killed, Aurora restarts it again. Thus, only one executor for a particular container number is running eventually.

**Comment by srkukarni** [comment]
Are we sure that if executor dies in a zombie container, internal aurora handlers within that container won't restart it?

**Comment by huijunw** [comment]
Zombie container scenario is hard to re-produce. I would suggest enable the proposed implementation and wait for the zombie container to appear to verify.

**Comment by billonahill** [comment]
@huijunw before going to far down the path of working around this from the Heron side, could you check in with the Aurora team to see where they are towards fixing the root cause. They had previously planned to work on this is Q2.

**Comment by huijunw** [comment]
All right @billonahill

**Comment by huijunw** [comment]
we confirmed with aurora team that aurora does not restart the zombie container. aurora team told us, if a new container is scheduled, the old zombie is already marked as `task lost` in aurora state, thus aurora does restart the `task lost` old zombie if it dies. @srkukarni

**Comment by huijunw** [comment]
The aurora team rejected the heron assumption 'there are no multiple same containers at one time point'. And the customers requested to raise priority of this issue. We plan to provide a PR to implement the above proposed solution. @srkukarni @objmagic @maosongfu thoughts?

**Comment by srkukarni** [comment]
@huijunw Could you tell whats the proposed solution? Is this the one thats mentioned in the first post(TMaster killing container). Also could you add more details about the mechanics of how this will be done in a general manner(aka non aurora specific). Thanks!

**Comment by huijunw** [comment]
Yes, in the first post. @srkukarni 
The basic idea is:
when Tmaster receives registration from the two same stmgrs, Tmaster sends http request to heron-shell endpoint '/killexectuor' of both containers. The heron-shell kill its parent heron-executor. This approach is non aurora specific.

**Comment by srkukarni** [comment]
Looking forward to the pr!

**Comment by objmagic** [comment]
@srkukarni 

We have a tentative implementation that we tested a bit on local environment. The patch is here. Does the implementation look OK?

https://github.com/twitter/heron/compare/huijunw/testLocalZombie...objmagic:huijunw/testLocalZombie?expand=1

**Comment by kramasamy** [comment]
@huijunw - one more possible probably "simple" solution (this assumes that zombie container lost connection to other containers). In the heartbeat sent to TMaster from stmgr include the number of active connections to other containers. For a zombie container, it might be 0 or very low and TMaster is also getting pings from container Y (which is reincarnation of X). When these two conditions satisfy - send a kill to the zombie container. The advantage of this approach is that it does not have to kill the new container. thoughts?

**Comment by huijunw** [comment]
@kramasamy i think the new stmgr has 0 connection count.
the new stmgr tries to register tmaster to obtain pplan but fails due to old zombie stmgr holding the tmaster connection. so the new stmgr does not have pplan and has 0 connection to the other containers.

**Comment by srkukarni** [comment]
@huijunw The proposed change
1) in tmaster cleanup httpclient and asyncdns
2) Add more logging
3) What are the changes in the LocalScheduler?

**Comment by objmagic** [comment]
@srkukarni @kramasamy @huijunw let's move discussion to https://github.com/twitter/heron/pull/2480

**Comment by objmagic** [comment]
@srkukarni your comments have been addressed
