### ISSUE TITLE
Compiling via Docker fails when using Ubuntu 16.04 container

### ISSUE THREAD

**Issue by tomncooper** [twitter/heron#2206]
The current `docker/compile/Dockerfile.ubuntu16.04` results in a container that fails to compile Heron as `libtool` cannot be found. It seems the issue is the wrong package name for `libtool` in the `apt-get install` command. It should be `libtool-bin` not `libtool`.

I have tested this and with this change it compiles successfully.

**Comment by kramasamy** [comment]
@tomncooper  - please send a PR for this fix.
