### ISSUE TITLE
Outgoing tuple from instance does not have size limit

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#2218]
See https://github.com/twitter/heron/blob/master/heron/instance/src/java/com/twitter/heron/instance/OutgoingTupleCollection.java#L127

It is true that if outgoing tuple has size larger than max data tuple size, we will open a new initialize a tuple. However, support the `HeronDataTuple` is 400MB large (as we observed in production environment), this tuple will still be created and sent to stream manager. However, stream manager on the other end will drop this huge size because our configuration.

If I'm right about the above observation, we should also limit the size of the tuple an instance could send out. This issue is causing problem because sending a huge tuple from instance to stream manager could make memory pool of that stream manager bloat up instantly.

cc: @srkukarni @huijunw

**Comment by srkukarni** [comment]
If I look at the code, there are already parameters controlling the size of HeronTupleSet(which is actually just a collection of HeronDataTuple). The issue arises when one HeronDataTuple is so large that it blows away all these limits.
IMO the way to solve this would be some sort of setting inside the instance that controls what is the largest size of HeronDataTuple allowed. And throw an error to the user if the user's emit is larger than that. Thoughts?

**Comment by huijunw** [comment]
agree @srkukarni . Throwing an error lets user know the tuple is too large.

**Comment by srkukarni** [comment]
The question is whether this should be made configurable? And if so, how. Might be something worthwhile in the API.

**Comment by objmagic** [comment]
@srkukarni see #2224 for a fix. We are not making it configurable. Just check if a single data tuple could be larger than the size limit of a set of data tuple.
