### ISSUE TITLE
Heron support for CoAP

### ISSUE THREAD

**Issue by naveenkumarmarri** [twitter/heron#2323]
Hi,

I'm working on IoT project where I receive datastream in CoAP protocol.
I want to process the data in Heron by doing some transformations on top of it.
Is it possible to integrate CoAP protocol objects to heron?

**Comment by srkukarni** [comment]
Hi Naveen,
It is certainly possible to integrate CoAP protocol inside Heron. Heron Spouts/Sources are general enough that one can connect to any data source/data type/protocol.
Are you already looking at some CoAP libraries to integrate with? It should be a fairly straightforward thing to construct a Heron source from that library.

**Comment by naveenkumarmarri** [comment]
I'm looking at californium.
Can you suggest some good implementations? My CoAP server is running on NodeJS and I want to build a CoAP listener at heron side and pass it on spout.
Can you point me to some references for this if available?

**Comment by srkukarni** [comment]
I'm assuming that you are running the CoAP server in UDP setting? In that
case something like UDPConnector
<https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/UDPConnector.java>
could
work.

**Comment by naveenkumarmarri** [comment]
Hi,

I'm able to pull data from coap server by observing the URI.
However I'm not able to get how to pass the URI configuration to the ISpout class.
Can you please help me on this or share some example how it is done?

**Comment by srkukarni** [comment]
You can put this uri information(assuming its a string), in the constructor
of the spout. For example take a look at
https://github.com/twitter/heron/blob/master/examples/src/java/com/twitter/heron/examples/TaskHookTopology.java
Here the AckingTestWordSpout is constructed without arguments. You can pass
the uri information here and then this will be carried over to the runtime.
