### ISSUE TITLE
python unit test failure is not detected

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#2328]
The current master branch doesn't report any failed python unit test. 

For very simple and obvious  failing test case, bazel still passes it:

```
  def test_sample(self):
    self.assertFalse(True);
```

And we also tried the following things in the unit test `//heron/statemgrs/tests/python:statemanagerfactory_unittest`:

- Put a time.sleep(10) in the test method 
- Raise an exception explicitly

But we observed the whole test class can still quickly finish and pass in 1s.

This is a big problem that any potential problematic python code will not be detected.

**Comment by srkukarni** [comment]
@aahmed-se has ideas about how this can be debugged.

**Comment by aahmed-se** [comment]
This is not a unit this requires zookeeper instances running and providing ssh access , this should be removed from unit test folder or be rewritten with mocks

**Comment by nlu90** [comment]
@aahmed-se I've change the `statemanagerfactory.py` code to make it only create object but not actually connecting to zk: #2327 

The issue here is why in an obvious failure test case, bazel doesn't report the failure.

**Comment by aahmed-se** [comment]
@nlu90 can you clarify what you mean, are you are converting it to real unit test case and it's not reporting errors as expected ?

**Comment by nlu90** [comment]
@aahmed-se  Yes. I'm converting it to a real unit case and making the test fail on purpose. But the failure is not reported.

**Comment by maosongfu** [comment]
@aahmed-se @nlu90 I have encountered this issue and **I doubt whether those python test methods, like ` def test_all_zk_supports_comma_separated_hostports(self)`, are executed**. I tried two changes:
- I put a `time.sleep(10)` in one test method but the whole test class can still quickly finish and pass in 1s. 
- I also tried to raise an exception explicitly and the test can still pass.

**Comment by aahmed-se** [comment]
the issue seems to bazel not running the tests at all, the issue seems to be happening since the bazel upgrade

**Comment by maosongfu** [comment]
@kramasamy Do you know any conflicts/issues preventing running python tests with the bazel upgrade?

**Comment by kramasamy** [comment]
I don’t think so - let me investigate and see.

**Comment by srkukarni** [comment]
One of the things we found was that the behaviour is normal prior to pex upgrade.
So we are looking at what went wrong in the pex upgrade

**Comment by srkukarni** [comment]
The fix has been found. pr coming soon

**Comment by srkukarni** [comment]
This has been fixed

**Comment by nlu90** [comment]
Thanks for fixing the issue!
