### ISSUE TITLE
Routing for the Heron UI on Kubernetes is broken

### ISSUE THREAD

**Issue by lucperkins** [twitter/heron#2443]
The Heron UI starts up just fine on Kubernetes (I've tried it on both GKE and Minikube) but there appears to be a problem with URL routing via the Kubernetes proxy. When clicking on links for **logs**, **job**, and **exceptions** for a specific Heron instance, instead of going to the appropriate page, this JSON object is returned:

```json
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/metrics",
    "/version"
  ]
}
```

This JSON response is essentially the 404 response from the Kubernetes API server, which suggests that the current Heron UI routing scheme may be incompatible with k8s.

**Comment by srkukarni** [comment]
This looks to be working in the current verison.
