### ISSUE TITLE
unify python dependency version

### ISSUE THREAD

**Issue by huijunw** [twitter/heron#2455]
For same package, a unique version is better to build in a customized environment.

for example
$ grep -ri requests== heron
heron/shell/src/python/BUILD:        "requests==2.11.1",
heron/tools/cli/src/python/BUILD:      "requests==2.12.3",
heron/tools/ui/src/python/BUILD:        "requests==2.11.1",

there are two versions for the same package. In our build environment, we have to make the dependency in WORKSPACE then customize them. A unique version may help to make this customization easier.

@objmagic @srkukarni @maosongfu thoughts?

**Comment by srkukarni** [comment]
+1 for this

**Comment by objmagic** [comment]
done
