### ISSUE TITLE
Heron Kubernetes Deployment does not work if Kubernetes is in containerized environment

### ISSUE THREAD

**Issue by mjschmidt** [twitter/heron#2500]
heron/deploy/kubernetes/general/bookkeeper.yaml

bookkeeper yaml could use some work. Will not work if Kubernetes worker nodes are containerizered due to the way bookkeeeper (apache distributed log) is attempting to port out of the container.

`containers:

        - name: bookie

          image: apachedistributedlog/distributedlog:0.5.0

          resources:

            requests:

              memory: "3Gi"

              cpu: "1000m"

            limits:

              memory: "5Gi"

              cpu: "2000m"

          # use the patched entrypoint.sh - it will automatically created the desired distributedlog namespace

          command: [ "/bin/bash", "/opt/distributedlog/bin/entrypoint.sh" ]

          args: ["/opt/bookkeeper/bin/bookkeeper", "bookie"]

          ports:

            - name: client

              containerPort: 3181

              # we are using `status.hostIP` for the bookie's advertised address. export 3181 as the hostPort,

              # so that the containers are able to access the host port

              hostPort: 3181`

**Comment by sijie** [comment]
Created apache/bookkeeper#681 for providing a yaml file to run bookkeeper using StatefulSets.
