### ISSUE TITLE
Heron admin UI does not work in offline environment

### ISSUE THREAD

**Issue by nicknezis** [twitter/heron#2509]
React and a few other javascript libraries are being referenced from cloudera cdn which fails in an offline (no internet) environment.

[Cloudera reference in HTML template](https://github.com/twitter/heron/blob/bedb3adee18aa415c263c27d0d211467fbcbad41/heron/tools/ui/resources/templates/application.html#L18)

**Comment by mjschmidt** [comment]
https://github.com/twitter/heron/pull/2513
Same pull request. Use one of these.

**Comment by mjschmidt** [comment]
#2513 has passed all checks, please use this pull request. Thanks.
https://github.com/twitter/heron/pull/2513

**Comment by kramasamy** [comment]
fixed in #2513
