### ISSUE TITLE
Unneeded dependency execute the topology main class locally

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#2518]
Here, https://github.com/twitter/heron/blob/master/heron/tools/cli/src/python/execute.py#L101,
we found that to execute a heron tar locally, it would add `heron-instance.jar` into classpath:
`os.path.join(tmpdir, "heron-instance.jar"),`

However,
1. it seems `heron-instance.jar` should not be included into the classpath to execute the topology main class locally.
2. the files in `tmpdir` are extracted from `topology_tar`, and `heron-instance.jar` should not be included in the `topology_tar`. In other words, it is adding an non-existing file into the classpath.

Did I miss anything? Or should we just remove this unneeded denpendency?

**Comment by maosongfu** [comment]
@srkukarni @kramasamy

**Comment by srkukarni** [comment]
It should be removed

**Comment by kramasamy** [comment]
It is not needed.

**Comment by maosongfu** [comment]
#2520
