### ISSUE TITLE
Current heron print_usage does not match the actual usages 

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#2530]
In https://github.com/twitter/heron/pull/2471,the command-line arguments were changed to be passed in a key-value fashion.
However, the print_usage does not reflect this change:
https://github.com/twitter/heron/blob/master/heron/executor/src/python/heron_executor.py#L47

The `print_usage()` should be updated as well.

**Comment by maosongfu** [comment]
@jerrypeng @srkukarni

**Comment by nwangtw** [comment]
seems completed.
