### ISSUE TITLE
current Docker container needs to be updated to run in static environment

### ISSUE THREAD

**Issue by mjschmidt** [twitter/heron#2575]
https://github.com/twitter/heron/pull/2513

container should be heron/heron:latest

also side note, when is the new container coming out? I hear it is half the size of the old heron container. What is the rough guesstimate for the size of the new container?

**Comment by kramasamy** [comment]
@mjschmidt - yes, we have reduced the size of the docker container using slim debian8. We are planning to release in the next iteration.

**Comment by mjschmidt** [comment]
Okay, so what about the code changes made in this pull request? Anyway to get them into the current heron container?

**Comment by mjschmidt** [comment]
@kramasamy

**Comment by kramasamy** [comment]
Is it not in 0.17.0 release?

**Comment by mjschmidt** [comment]
This works. I don't know what was going on with my docker. Sorry guys. Can close
