### ISSUE TITLE
Configs generated in getComponentConfiguration() are not translated

### ISSUE THREAD

**Issue by nwangtw** [twitter/heron#2585]
Users with storm API can override the function getComponentConfiguration() to pass configs. After the new config code changes, the component configs come from this function are not translated to Heron config.

This issue should affect users using storm/backtype API only.
It is likely to affect users using 0.16 and 0.17.

**Comment by maosongfu** [comment]
Do you think we should add back the check of "TICK_TUPLE_SECS" in BoltInstance here: https://github.com/twitter/heron/blob/master/heron/instance/src/java/com/twitter/heron/instance/bolt/BoltInstance.java#L305, for backward compatibility to avoid making such thing broken in future?

cc: @jerrypeng, what do you think?

**Comment by nwangtw** [comment]
I think this should be a simple fix and we are close to cover all edges. So it is not necessary to have the check I think, plus the code would be confusing.

Unit changes can be scary. I feel the root cause was the config translation. Pretty much all configs have the same names in API layer and core layer, so bugs like this (lost in translation) were hidden. tick_tuple_secs might be the first one that has different keys in different layers so it shows up this time.

**Comment by maosongfu** [comment]
@nwangtw sounds good.

**Comment by nwangtw** [comment]
fixed in https://github.com/twitter/heron/pull/2592
