### ISSUE TITLE
Kubernetes Heron UI still has some (but few now) issues

### ISSUE THREAD

**Issue by mjschmidt** [twitter/heron#2587]
Built heron UI on Google Container Platform and it looks like the way it is setting the height is not correct. It is setting the height of the Topology to NaN. Here is a screen shot of what I see, not sure exactly what the issue is yet. May need some further investigation?

Using the latest container for the Kubernetes build.

![image](https://user-images.githubusercontent.com/6544930/33234576-4b3eec90-d1f7-11e7-8fd2-96f1017a33de.png)

**Comment by cckellogg** [comment]
What is the state of the topology? This will happen when the state is unknown. The tracker will return an empty logical and physical plan. The ui should probably be more graceful in this situation.

**Comment by mjschmidt** [comment]
Chrome issue again -_-... yikes.
