### ISSUE TITLE
use yaml lib to write override.yaml

### ISSUE THREAD

**Issue by huijunw** [twitter/heron#2595]
we found an bug in https://github.com/twitter/heron/pull/2588/files 
which lost a space after `:` in override.yaml

I would suggest using yaml lib to generate yaml conent

cc @maosongfu @nwangtw 

More context:
This will generate a wrong content in override.yaml - the content is not a in valid yaml format.
It will throw exceptions:
```
01:57:03 Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
01:57:03        at com.twitter.heron.common.config.ConfigReader.loadFile(ConfigReader.java:78)
01:57:03        at com.twitter.heron.spi.common.ConfigLoader.loadConfig(ConfigLoader.java:37)
01:57:03        at com.twitter.heron.spi.common.ConfigLoader.loadConfig(ConfigLoader.java:67)
01:57:03        at com.twitter.heron.scheduler.SubmitterMain.loadConfig(SubmitterMain.java:271)
01:57:03        at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:309)```

**Comment by maosongfu** [comment]
Also, could we add unit tests or integration tests to catch this issue and avoid it in future?

**Comment by nwangtw** [comment]
Good find~

**Comment by nwangtw** [comment]
fixed in https://github.com/twitter/heron/pull/2596
