### ISSUE TITLE
Don't allow people updating the UI container to add code that calls out to the internet

### ISSUE THREAD

**Issue by mjschmidt** [twitter/heron#2642]
I made changes in an earlier issue to fix the fact that the UI could not be seen in offline mode, and a recent change has caused the UI to call out to the internet again. Can we change the build process to make sure that all files for the UI are statically called?:

http://fonts.googleapis.com/css?family=Trykker

I don't want to become the maintainer of keeping the UI working in static/offline mode.

**Comment by mjschmidt** [comment]
https://github.com/twitter/heron/blob/12425366a9ade8501675c1e29c2ea34cb36044cb/heron/tools/ui/resources/static/css/main.css

Its this file, my contract doesn't currently technically allow me to make changes to this project yet.

**Comment by mjschmidt** [comment]
This looks like its not actually a recent change, it was august. So it must be a mirroring issue on our side. I will make the change in my free time at home.

**Comment by kramasamy** [comment]
@mjschmidt - we don't remember adding anything to UI so far actually.

**Comment by kramasamy** [comment]
Ok - let us know if we need to fix anything!

**Comment by mjschmidt** [comment]
Remember all. Always use at least a semi updated version of chrome -_- my bad all
