### ISSUE TITLE
setup-intellij.sh fails in loop

### ISSUE THREAD

**Issue by sreev** [twitter/heron#2663]
$ ./scripts/setup-intellij.sh
ERROR: File ./scripts/compile_env/env_exec.sh is not found.
Run ./bazel_configure.py first.

$ ./bazel_configure.py
Platform Darwin
Using C compiler          :	/usr/bin/clang (9.0.0)
Using C++ compiler        :	/usr/bin/clang++ (9.0.0)
Using C preprocessor      :	/usr/bin/cpp (9.0.0)
Using C++ preprocessor    :	/usr/bin/cpp (9.0.0)
Using linker              :	/usr/bin/ld
Using Automake            :	/usr/local/Cellar/automake/1.15.1/bin/automake (1.15.1)
Using Autoconf            :	/usr/local/Cellar/autoconf/2.69/bin/autoconf (2.69)
Using Make                :	/usr/bin/make (3.81)
Using CMake               :	/usr/local/Cellar/cmake/3.10.1/bin/cmake (3.10.1)
Using Python              :	/Users/svaddi/anaconda/bin/python3.6 (3.6.1)
Using Libtool             :	/usr/local/Cellar/libtool/2.4.6_1/bin/glibtool (2.4.6)
Using archiver            :	/usr/bin/ar
Using coverage tool       :	/usr/bin/gcov
dwp                       :	not found, but ok
Using nm                  :	/usr/bin/nm
objcopy                   :	not found, but ok
Using objdump             :	/usr/bin/objdump
Using strip               :	/usr/bin/strip

$ ./scripts/setup-intellij.sh
ERROR: File ./scripts/compile_env/env_exec.sh is not found.
Run ./bazel_configure.py first.

**Comment by sreev** [comment]
@kramasamy recollected that env_exec.sh file is removed.  commenting out the check for it in the script file. i ran into the python3 incompatability error.

$ ./scripts/setup-intellij.sh
changing to /Users/svaddi/SreeVaddi/source/github/sreev/heron/scripts/..
INFO: Analysed 690 targets (14 packages loaded).
INFO: Found 690 targets...
ERROR: /Users/svaddi/SreeVaddi/source/github/sreev/heron/tools/rules/pex/BUILD:48:1: Bootstrapping pex //tools/rules/pex:pex_wrapper failed (Exit 100)
ERROR: The executable /var/folders/40/_cbf9y0936x52h1fk8tlvrlm0000gn/T/pex.XXXXX.LhCeznXS/venv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/private/var/tmp/_bazel_svaddi/d87af79cadec1a9b05b7625062a16274/execroot/__main__' (should be '/var/folders/40/_cbf9y0936x52h1fk8tlvrlm0000gn/T/pex.XXXXX.LhCeznXS/venv')
ERROR: virtualenv is not compatible with this system or executable
dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /var/folders/40/_cbf9y0936x52h1fk8tlvrlm0000gn/T/pex.XXXXX.LhCeznXS/venv/bin/python
  Reason: image not found
INFO: Elapsed time: 3.915s, Critical Path: 1.84s
FAILED: Build did NOT complete successfully
WARNING!!! - bazel build failed - intellij setup may not be consistent
Path is /Users/svaddi/SreeVaddi/source/github/sreev/heron
Generating IDEA project...
find: contrib: No such file or directory
Done. IDEA module file: heron.iml

Could not locate IntelliJ IDEA. Manually open /Users/svaddi/SreeVaddi/source/github/sreev/heron as a project in IDEA.

**Comment by kramasamy** [comment]
If you could remove the check for env_exec.sh - in setup-intellij.sh and send a PR - it will be great. We have to make the entire compilation work with python3 - currently works with python2.7+ but not python3

**Comment by sreev** [comment]
Commenting out the check for file 'env_exec.sh' and using 'sudo', makes the setup successfully.
Project opened in intellij successfully.
Will update the documentation, later.

**Comment by kramasamy** [comment]
@sreev - it will be great if you could sent out the PR for removing env_exec.sh?
