### ISSUE TITLE
Ability to configure client classpath

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#271]
While integrating with hadoop related systems, loading jars at runtime is preferred. For e.g. by allowing user to provide a `--classpath` option or setting `CLASSPATH` env variable. If there is a workaround, please share the steps to configure client's classpath (to be used by Launcher and Uploader). 
Thanks !

**Comment by ashvina** [comment]
@kramasamy this issue can be closed now?

**Comment by kramasamy** [comment]
yes. Fixed in #1245
