### ISSUE TITLE
HttpUploader documentation

### ISSUE THREAD

**Issue by jerrypeng** [twitter/heron#2715]
Documentation for the HttpUploader.  Should be very simple.  Add a section in 

https://twitter.github.io/heron/docs/operators/deployment/uploaders/

Code:

https://github.com/twitter/heron/blob/master/heron/uploaders/src/java/com/twitter/heron/uploader/http/HttpUploader.java

Example of conf:

https://github.com/twitter/heron/blob/master/heron/config/src/yaml/conf/standalone/uploader.yaml

**Comment by erenavsarogullari** [comment]
Hi @jerrypeng 
Thanks to create this.
I was thinking to address HttpUploader documentation so please assign to me and will address it ;)

**Comment by jerrypeng** [comment]
@erenavsarogullari that would be great thanks!

**Comment by jerrypeng** [comment]
@erenavsarogullari fyi you can also use heron's API server as a file server for the HttpUploader to upload topology package/jars to.  If you can briefly mention that in the docs.  Thanks!

You can run the API Server as such:

${HOME}/.heron/bin/heron-apiserver \
--cluster standalone \
--base-template standalone \
-D heron.statemgr.connection.string=<zookeeper_host:zookeeper_port> \
-D heron.nomad.scheduler.uri=<scheduler_uri> \
-D heron.class.uploader=com.twitter.heron.uploader.http.HttpUploader \
--verbose

**Comment by erenavsarogullari** [comment]
@jerrypeng Sure, Will mention this as well. Thanks

**Comment by erenavsarogullari** [comment]
@jerrypeng This issue has been addressed via PR #2750 so can be closed. Thanks
