### ISSUE TITLE
IntelliJ IDEA setup script fails with checkstyle_java failed (Exit 2)

### ISSUE THREAD

**Issue by asudhindra** [twitter/heron#2737]
Hi, I just pulled the heron project and on trying to execute the `setup-intellij.sh` script, i get an error with the following message:

```
ERROR: /Users/arunsudhindra/Documents/Development/heron/heron/tools/java/src/com/twitter/bazel/checkstyle/BUILD:12:1: Executing extra_action //tools/java:checkstyle_java on //tools/java/src/com/twitter/bazel/checkstyle:checkstyle_java failed (Exit 2)
Starting audit...
[ERROR] /private/var/tmp/_bazel_arunsudhindra/7f42e50fa95a6670b3ec42049552861c/execroot/__main__/tools/java/src/com/twitter/bazel/checkstyle/JavaCheckstyle.java:116: Line has trailing spaces. [RegexpSingleline]
```

On changing the `JavaCheckstyle.java` class to remove the trailing spaces on line 116

```
Predicates.containsPattern("external") // from external/ directory for bazel
```

I'm able to see a build complete successfully. Can I PR this change? It seems to be along the lines of an older issue raised here: https://github.com/twitter/heron/issues/1369

**Comment by kramasamy** [comment]
@asudhindra - please do submit a PR. thanks.

**Comment by asudhindra** [comment]
@kramasamy Done. Please review when you get the chance. Thanks!

**Comment by maosongfu** [comment]
In fact, I have submitted a pull request for this:#2729 previously but could not pass the ci-tests due to some flaky tests. I will close mine.
