### ISSUE TITLE
logging message error

### ISSUE THREAD

**Issue by aahmed-se** [twitter/heron#2777]
this code in https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/utils/PackingUtils.java#L61 is incorrect , ``` instanceCpu > maxContainerResources.getCpu()``` returns a boolean not a number whole.

Also Math.round will make cpu request of less then whole number like 0.5 to be a whole number which is not the behavior expected.

```
double instanceCpu = Math.round(PackingUtils.increaseBy(
        instanceResources.getCpu(), paddingPercentage));
    if (instanceCpu > maxContainerResources.getCpu()) {
      throw new PackingException(String.format(
          "This instance requires containers with at least %s cpu cores. The current max container"
              + "size is %s cores",
          instanceCpu > maxContainerResources.getCpu(), maxContainerResources.getCpu()));
    }
```

**Comment by ashvina** [comment]
Is can take a look at this issue. There a few places where a whole number value of cpu is assumed. It seems to me that we can get rid of this assumption.

**Comment by ashvina** [comment]
This is what I have seen in the code so far. A container will always request for a whole number of cores. However, the instance inside the container may still be requesting 0.5 core. 
For e.g. The default value of `heron.resources.instance.cpu` is 1. So the default container (of 4 instances) will request 4 cores. If the value of `heron.resources.instance.cpu` is changed to `0.5`, the same default container (4 instances) will request 2 cores, or 3 cores for 5 instances. This seems fine to me.

Hi @aahmed-se, can you provide more details about the `whole number` test-case you mentioned in the description?

**Comment by aahmed-se** [comment]
Existing topology with this config  fails
```
        com.twitter.heron.api.Config.setContainerCpuRequested(conf, 0.5f);
``` 
```
[2018-03-13 21:24:41 +0000] [ERROR]: This instance requires containers with at least true cpu cores. The current max containersize is 0.5 cores
```

**Comment by aahmed-se** [comment]
this is standalone mode on a local machine, not sure what is the configuration for it

**Comment by ashvina** [comment]
Discussed with @aahmed-se. `RoundRobinPacking` supported the behavior in which a larger instance can be forced in a small container. `RRPacking` packing has been deprecated (75c25a08bb5ebd10b76f7b5ededd9eb2f4e9180a). `ResourceComplaintRRPacking` does not allow this. Whole-number-core does not seem to be the issue. 

I will fix the logging issue in a PR.

**Comment by aahmed-se** [comment]
We can close this issue, resolution has been discussed offline.
