### ISSUE TITLE
Move Heron to an independent open source foundation

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#606]
Placeholder for tracking the discussions about moving Heron to an independent open source foundation

**Comment by venkateshs** [comment]
+1 to apache.

**Comment by lewiskan** [comment]
Twitter is a founding member of Cloud Native Computing Foundation ( https://cncf.io/ ).  Any experiences with CNCF, or pros/cons compared to Apache? Heron could become the 3rd project next to Kubernetes and Prometheus.

**Comment by bradbiddle** [comment]
The ASF proposal looks pretty compelling to me, FWIW, but some other options that may not be on your radar:

- Joint Development Foundation <jointdevelopment.org> provides an easy and inexpensive structure for projects to launch under an independent non-profit framework (disclosure: I'm on the Board)

- Launching as an independent non-profit entity is simpler and cheaper than most people think, particularly if you use an association management firm to handle the details, and gives you lots of control of your own destiny. 

--Brad

**Comment by caniszczyk** [comment]
Looks like this is happening at the ASF so this issue can be closed IMHO: https://wiki.apache.org/incubator/HeronProposal

**Comment by kramasamy** [comment]
yes indeed.
