### ISSUE TITLE
Heron in Kubernetes

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#617]
Kubernetes is next generation scheduler by Google. Heron in Kubernetes using dockers will be welcome addition.

**Comment by paralin** [comment]
Interested in doing this, will see if I can get it working

**Comment by kramasamy** [comment]
Awesome! Go for it!

**Comment by kramasamy** [comment]
@paralin - any update on this? if you need help let us know.

**Comment by moomou** [comment]
Hello. I am interested in this. Please let me if there's anything that needs help.

**Comment by objmagic** [comment]
@moomou feel free to go ahead! You can always discuss with us on [mailing list](https://groups.google.com/forum/#!forum/heron-users), join [Heron user Slack group](https://heronusers.slack.com/), or continue on this GitHub issue.

**Comment by kramasamy** [comment]
@moomou @prabhuinbarajan @paralin - all expressed interest for running Heron on Kubernetes. Please let me know so that we can have an initial meeting and colloborate on this effort.

**Comment by moomou** [comment]
@kramasamy How would we like to do the initial meeting? I imagine a video group chat would be really hard given everyone's schedule.

Would listing tasks in bullet points here be more achievable? Haven't jumped in yet, btw.

**Comment by paralin** [comment]
I plan to work on this in the coming weeks, not quite to the stream processing part of my project yet, but when I get there, I'll likely build a Kubernetes integration for Heron if nobody else has yet.

With Kubernetes you have a few tools that could make Heron work nicely. It seems you have pluggable schedulers in Heron which is ideal for Kubernetes, really all you'll need to do is write some code to interface with the Kubernetes API. In every Kubernetes container on default you get a file with a token used to authenticate against the API at 10.0.0.1. From there it's fairly easy to implement your own scheduler logic for pods.

**Comment by kramasamy** [comment]
@paralin @moomou @prabhuinbarajan - we could have a video chat and I can add you guys to the committer slack channel - heronstreaming.slack.com

**Comment by kramasamy** [comment]
@paralin @moomou - I have invited both of you the committer slack channel. Once you accept the invite - we can discuss it and have an initial video chat.

**Comment by waitingkuo** [comment]
Will the discussion or development be transparent? Sorry I'm not familiar with Heron. I was a Storm user and I'm currently trying to port other frameworks to kubernetes now. Quite interested in your approach, would be a good inspiration when I port other frameworks. Got the chance to audit or contribute?

**Comment by kramasamy** [comment]
Prabhu/Palin/Paul - please include Wei in your kubernetes development.

**Comment by kramasamy** [comment]
@waitingkuo - we have invited you to our slack contributor's channel.

**Comment by nicknezis** [comment]
Any updates?

**Comment by kramasamy** [comment]
@nicknezis - initial version of heron in k8s is already in 0.14.9. We are adding documentation and tutorial in the upcoming version. Please check #1946

**Comment by nicknezis** [comment]
Awesome thanks!

**Comment by srkukarni** [comment]
This has been subsumed by https://github.com/twitter/heron/pull/1970

**Comment by kramasamy** [comment]
Heron already runs in Kubernetes - closing the issue.
