### ISSUE TITLE
Linkchecker fails to check some links

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#770]
Go to `website/content/docs/developers/data-model.md` and change `/api/com/twitter/heron/api/tuple/Tuple.html` to `/api/foobar/com/twitter/heron/api/tuple/Tuple.html` and run 'make site'.

Linkchecker passes. It doesn't test the link. WHen I add `-v` to the linchecker command and comment out `rm -f $OUT_FILE` from `website/scripts/linckchecher.sh` you see that the link is not checked because it appears external:

```
http://twitter.github.io/heron/api/foobar/com/twitter/heron/api/tuple/Tuple.html;
file:///Users/billg/ws/git/heron/website/public/docs/developers/data-model/index.html;;
filtered;;
The URL is outside of the domain filter, checked only syntax.;
True;
http://twitter.github.io/heron/api/foobar/com/twitter/heron/api/tuple/Tuple.html;
14;82;"Javadoc
```

Ideally we could map `twitter.github.io/heron` in linkchecker.

cc/ @lucperkins

**Comment by objmagic** [comment]
close. #797 and #841 will fix this.
