### ISSUE TITLE
Image on Deploying Heron doc page is 404

### ISSUE THREAD

**Issue by efenderbosch** [twitter/heron#813]
On this page:
https://twitter.github.io/heron/docs/operators/deployment/

This image is 404.

https://twitter.github.io/heron/img/heron-deployment.png

**Comment by billonahill** [comment]
Thanks for the report @efenderbosch.

Relates to #747. @kramasamy do you have that image?

**Comment by objmagic** [comment]
@billonahill I got it, and I'll fix it soon.
