### ISSUE TITLE
Move to bazel2

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#816]
Heron should compile with bazel2 versions.

**Comment by jolestar** [comment]
same problem, comple with bazel:0.2.3

heron/WORKSPACE:15:1: maven_server rule //external:twitter-maven's name field must be a legal workspace name.

**Comment by kramasamy** [comment]
yes - we are working on getting this fixed.

**Comment by daxwang** [comment]
bazel 0.1.2 not support http_proxy. so i update it  to the lastest version.0.2.3, but  error when complie heron with  bazel 0.2.3
ERROR: WORKSPACE:15:1: maven_server rule //external:twitter-maven's name field must be a legal workspace name.
so please fix it  immediately, thx

**Comment by kramasamy** [comment]
Fixed in #869
