### ISSUE TITLE
bazel build error

### ISSUE THREAD

**Issue by smxysu3** [twitter/heron#829]
hi 
when I  Build the project :
**bazel build --config=ubuntu heron/...**

------------------------------------------
ERROR: /home/su3/opensrc/heron/heron/shell/src/python/BUILD:17:1: null failed: _pex failed: error executing command bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex --entry-point heron.shell.src.python.main bazel-out/local_linux-fastbuild/bin/heron/shell/src/python/heron-shell.pex ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by kramasamy** [comment]
@smxysu3 - Please follow the instructions for compiling on Ubuntu and let us know. 

http://twitter.github.io/heron/docs/developers/compiling/linux/#building-on-ubuntu-14.04:34fe9f2d9cc3cd7e319ca75e7da08332

and let us know

**Comment by smxysu3** [comment]
@kramasamy - thanks ! 
because I did  not installed  "setuptools"

**Comment by dnk8n** [comment]
Hi all. Promising project, excited to get started. However, I have found quite a few dead links around the Heron project...

The link above (http://twitter.github.io/heron/docs/developers/compiling/linux/#building-on-ubuntu-14.04:34fe9f2d9cc3cd7e319ca75e7da08332) is dead.

Also, https://apache.github.io/incubator-heron/docs/developers/python/topologies/, the following do not work:
- https://github.com/twitter/heron/tree/master/heron/examples/src/python
- Almost all links under the 'Example topologies' section.

Trying to work out how I build a PEX file. Can anyone point me in the right direction?
