### ISSUE TITLE
Ubuntu：Failed to execute PEX file, missing compatible dependencies for: pyyaml

### ISSUE THREAD

**Issue by mlinge** [twitter/heron#831]
I study Heron on Ubuntu, but I'm in a bit of trouble. execute the "help submit Heron" command, there are the following errors。
`
Failed to execute PEX file, missing compatible dependencies for:
pyyaml
`
 I reinstall the Python and pyyaml, but the problem is still there, who can help me.

Thanks!

**Comment by kramasamy** [comment]
@mlinge - I was wondering if you try to compile the code and installed the prebuilt binaries. What version of ubuntu are you using? Ubuntu binaries work for Ubuntu versions >= 14.04

**Comment by mlinge** [comment]
My Ubuntu version is 16.04 LTS, Its version >=14.04.
I was using the "./xxx.sh --user" installed, did not use the compiled code, it's installed successfully。
execute "Heron help submit" command failed

**Comment by kramasamy** [comment]
@mlinge - we have not encountered this error before. It could be partially because we have not run heron in 16.04 at all.

@billonahill - any clues on why PEX might be complaining?

**Comment by billonahill** [comment]
@mlinge pex files include the dependencies (in this case pyyaml) so reinstalling it on your machine shouldn't make a difference. I would recommend looking at the version currently being bundled and checking its compatibility with your version of Ubuntu.

**Comment by nlu90** [comment]
We have this similar problem when compiling the binaries on one platform and executing it on another platform. One thing we can do is recompiling the whole heron project on your host, and then install the compiled the binaries.

**Comment by kramasamy** [comment]
@mlinge - checking if this issue is resolved so that we can close the issue.

**Comment by avitorovic** [comment]
I get the same error when running 'heron version', although I am using Ubuntu 14.04 (I upgraded from Ubuntu 12.04).

**Comment by kramasamy** [comment]
If you get a chance can you use the DockerFile.ubuntu14.04 and see if the error occurs. There is a script called 

docker/build-artifacts.sh

which you can use to build artifacts for ubuntu

cheers
/karthik

**Comment by avitorovic** [comment]
My OS is 32-bit, and that caused trouble. It seems I will have to install from the source.

**Comment by pradeep0605** [comment]
I am getting the same error :

$> heron
Failed to execute PEX file, missing compatible dependencies for:
psutil
pyyaml

Was there any fix for this ? I think I did heron-client-install-0.14.4-ubuntu.sh (without the --user) once, and after running this command, I am unable to run heron at all. Can someone please let me know what can be the problem here ? I am using ubutnu 14.04.
 
Thanks
Pradeep

**Comment by objmagic** [comment]
This is due to OS version issue. We will try to use low OS version to build releasing binary.
