### ISSUE TITLE
[Build Error]no such package '@thrift//jar'

### ISSUE THREAD

**Issue by longdafeng** [twitter/heron#832]
Thanks in advance.

Due to My build machine can't connect to maven.twttr.com.  I installed "org.apache.thrift:libthrift:jar:0.5.0-1" to my local maven repository.

How to work around this.

```
ERROR: /home/admin/heron/heron.github/heron/metricsmgr/src/thrift/BUILD:5:1: no such package '@thrift//jar': Failed to fetch Maven dependency: Could not transfer artifact org.apache.thrift:libthrift:jar:0.5.0-1 from/to thrift (http://maven.twttr.com): Connect to maven.twttr.com:80 timed out and referenced by '//heron/metricsmgr/src/thrift:thrift_scribe_java'.
ERROR: Loading failed; build aborted.
```

```
ls ~/.m2/repository/org/apache/thrift/libthrift/0.5.0-1/
libthrift-0.5.0-1.jar  libthrift-0.5.0-1.pom  libthrift-0.5.0-1-sources.jar  _remote.repositories
```

**Comment by kramasamy** [comment]
@longdafeng - you should not connect to maven.twttr.com. At the top of the repo - there is a WORKSPACE file, with the following entries - 

maven_server(
  name = "default",
  url = "http://central.maven.org/maven2/",
)

maven_server(
  name = "twitter-maven",
  url = "http://maven.twttr.com",
)

Remove the maven_server entry that has maven.twttr.com and try it. You should connect by default to maven central.

**Comment by longdafeng** [comment]
@kramasamy ， thanks

But still fail.
modify the WORKSPACE
At last, I modify the thrift version from 0.5.0-1 to 0.5.0

```
maven_jar(
  name = "thrift",
  #artifact = "org.apache.thrift:libthrift:0.5.0-1",
  artifact = "org.apache.thrift:libthrift:0.5.0",
  server = "default",
)
```
Then, pass the build, but I don't know whether libthrift 0.5.0 works fine or not?

**Comment by longdafeng** [comment]
at last

**Comment by kramasamy** [comment]
Reopening this - so that we can fix this. @billonahill or @maosongfu - any idea why thrift should 0.5.0-1?

**Comment by maosongfu** [comment]
It is more Twitter internal concern. BTW, the latest thrift 0.9.* is not compatible with 0.5.*

**Comment by billonahill** [comment]
@maosongfu Heron currently requires a patched version of thrift 0.5.0 that is only available at maven.twttr.com, which is a public repo. @longdafeng if you're environment can't connect there, you can download the artifact and upload it to your local maven repo.

**Comment by maosongfu** [comment]
Duplicated: #912

**Comment by phynman** [comment]
@billonahill  download the artifact and upload it to your local maven repo.
I am working on centos7 , how to put it to local maven repo ?  There is no maven repo when I build in my machine .

**Comment by billonahill** [comment]
@phynman bazel needs a maven repo to pull artifacts from. You either need access to maven.twttr.com and central.maven.org (see the `WORKSPACE` file), or you can use your own maven repo if you have one.

**Comment by phynman** [comment]
@billonahill  Thanks, I got it . I have already successful builded  in my centos7 machine,  but I can use the builded heron deploy into other machine ? How to do it ?  
Thanks !

**Comment by phynman** [comment]
Thanks , I got it  . I have successfully builded  it .

**Comment by kramasamy** [comment]
@phynman - since heron uses native code, you can build and deploy in the same platforms only. For example, if you build in centos7, you need to deploy in centos7 or above.

**Comment by phynman** [comment]
@kramasamy  Thanks ,  I  know it

**Comment by goldenhoo** [comment]
There is no  org.apache.thrift:libthrift:jar:0.5.0-1   in  the website  "http://maven.twttr.com  ". 
Has other website has it?

**Comment by goldenhoo** [comment]
@phynman , How to  fix libthrift-0.5.0-1.jar?

**Comment by goldenhoo** [comment]
There is no libthrift-0.5.0-1.jar  ( org.apache.thrift:libthrift:jar:0.5.0-1 )  in the website "http://maven.twttr.com ".
Has any website  it?

**Comment by goldenhoo** [comment]
Thanks in advance. 
  My question:
    goldens-MacBook-Air:heron golden$ bazel build --config=darwin heron/...
ERROR: /Users/golden/heron/heron/metricsmgr/src/thrift/BUILD:5:1: no such package '@org_apache_thrift_libthrift//jar': Failed to fetch Maven dependency: Could not transfer artifact org.apache.thrift:libthrift:jar:0.5.0-1 from/to org_apache_thrift_libthrift (http://maven.twttr.com): Connect to maven.twttr.com:80 timed out and referenced by '//heron/metricsmgr/src/thrift:thrift_scribe_java'.
ERROR: Analysis of target '//heron/metricsmgr/src/thrift:thrift-java' failed; build aborted.
INFO: Elapsed time: 13.361s

**Comment by kramasamy** [comment]
@goldenhoo - maven.twttr.com <http://maven.twttr.com/> is a twitter internal maven repository. You need to use the central maven repository. Wondering which version of Heron are you trying to compile.

cheers
/karthik

**Comment by billonahill** [comment]
`maven.twttr.com` is in fact a public repo and is used by heron only for `libthrift` (http://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/). See the WORKSPACE file. It does seem to be down though. I'm investigating.

**Comment by billonahill** [comment]
maven.twttr.com seems to be available again(https://www.webpagetest.org/result/170412_QX_15Z9/1/details/#waterfall_view_step1). I'm guessing there was an intermittent availability issue.

**Comment by billonahill** [comment]
FYI, dns appears to be incorrect in China:
https://www.whatsmydns.net/#A/maven.twttr.com

**Comment by objmagic** [comment]
https://www.whatsmydns.net/#A/maven.twttr.com DNS resolution of `maven.twttr.com` is poisoned in mainland China. IP address location is either in Italy or in Azerbaijan.

If anyone encounters this issue, you are advised to use proxy or VPN.
