### ISSUE TITLE
execute ./bazel_configure.py error

### ISSUE THREAD

**Issue by Jonathan-Wei** [twitter/heron#837]
hi,guys!
when I Build the project :
./bazel_configure.py
(MAC)
➜  heron git:(master) ./bazel_configure.py
Platform Darwin
Using C compiler          :	/usr/bin/clang (6.0)
Using C++ compiler        :	/usr/bin/clang++ (6.0)
Using C preprocessor      :	/usr/bin/cpp (6.0)
Using C++ preprocessor    :	/usr/bin/cpp (6.0)
Using linker              :	/usr/bin/ld

FAILED:  You need to have automake installed to build Heron.
Note: Some vendors install automake with a versioned name
(like /usr/bin/automake-4.8). You can set the AUTOMAKE environment
variable to specify the full path to yours.' 

➜  heron git:(master) echo $AUTOMAKE
/usr/local/Cellar/automake/1.15

**Comment by Jonathan-Wei** [comment]
No body help me?

**Comment by kramasamy** [comment]
@Jonathan-Wei - the simplest would be to get automake in your path and see if it works. Meanwhile we are working on finding the root cause of the issue.

**Comment by Jonathan-Wei** [comment]
@kramasamy 
I execute automake command.  
The command line display ：
automake:error:'configure.ac' is required

And I link automake to /usr/bin/automake

But the problem still exists

**Comment by Jonathan-Wei** [comment]
My system is Mac OS X Yosemite 10.10.5

**Comment by billonahill** [comment]
@Jonathan-Wei best way to debug this would be to follow the code be follow the code from this line in `bazel_configure.py`:
```
  env_map['AUTOMAKE'] = discover_tool('automake', 'Automake', 'AUTOMAKE', '1.9.6')
```

It calls `discover_tool`, which fails to find anything in `discover_program`. Add some print debugging in `discover_program` and `real_program_path` to uncover the issue: 
https://github.com/twitter/heron/blob/master/bazel_configure.py#L212

**Comment by Jonathan-Wei** [comment]
@billonahill 
I add some print to debugging in real_progream_path and which method!

```
path is /opt/local/bin
exe_file is /opt/local/bin/cmake
candidate is /opt/local/bin/cmake
isfile : False ,access enough: False :
is_exc method return is False
isfile : False ,access enough: False :
candidate is /opt/local/bin/cmake
isfile : False ,access enough: False :
is_exc method return is False
isfile : False ,access enough: False :
```

```
def which(program):
  def is_exe(fpath):
    print("isfile : %s ,access enough: %s :" % (os.path.isfile(fpath) , os.access(fpath, os.X_OK)))
    return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

  def ext_candidates(fpath):
    yield fpath
    for ext in os.environ.get("PATHEXT", "").split(os.pathsep):
      yield fpath + ext

  fpath, fname = os.path.split(program)
  print("fpath %s fname %s" %(fpath,fname))
  if fpath:
    if is_exe(program):
      return program
  else:
    for path in os.environ["PATH"].split(os.pathsep):
      print("path is %s " % path)
      exe_file = os.path.join(path, program)
      print("exe_file is %s" % exe_file)
      for candidate in ext_candidates(exe_file):
        print("candidate is %s " % candidate)
        print("is_exc method return is %s" % is_exe(candidate))
        if is_exe(candidate):
          return candidate

  return None
```

I execute os.path.isfile and os.access in python command return true,but why here return false

➜  heron git:(master) ✗ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isfile('/usr/local/bin/automake')
True
>>> os.access('/usr/local/bin/automake',os.X_OK)
True

➜  heron git:(master) ✗ ls -al /usr/local/bin/automake
lrwxr-xr-x  1 jonathanwei  admin  36  5 31 01:16 /usr/local/bin/automake -> ../Cellar/automake/1.15/bin/automake
➜  heron git:(master) ✗ cd /usr/local/Cellar/automake/1.15/bin
➜  bin git:(master) ✗ ls -al
total 1152
drwxr-xr-x   6 jonathanwei  admin     204  5 31 01:16 .
drwxr-xr-x  10 jonathanwei  admin     340  5 31 01:16 ..
-r-xr-xr-x   2 jonathanwei  admin   36873  5 31 01:16 aclocal
-r-xr-xr-x   2 jonathanwei  admin   36873  5 31 01:16 aclocal-1.15
-r-xr-xr-x   2 jonathanwei  admin  253233  5 31 01:16 automake
-r-xr-xr-x   2 jonathanwei  admin  253233  5 31 01:16 automake-1.15

Thanks!

**Comment by billonahill** [comment]
You're comparing two different things. `bazel_configure.py` is checking `/opt/local/bin/cmake`, but you're checking `/usr/local/bin/automake`.

**Comment by Jonathan-Wei** [comment]
@billonahill  
Oh,I'm Sorry!
I re-check it again! 
Thanks!
