### ISSUE TITLE
If I want use heron in centos6, should I do?

### ISSUE THREAD

**Issue by aaronshan** [twitter/heron#848]
I build heron by run 
```
$ docker/build-artifacts.sh centos7 master ~/centos
```
After I install it and submit Exclamation Topology,  I also get error like [#822](https://github.com/twitter/heron/issues/822). 
I also get this error in centos7 and I resolved it by installing libunwind. 
when I try use same method to resolve it, but I failed.  This problem also caused by lacking other native c++ dependency ?
If I want use heron in centos6, should I do?

**Comment by maosongfu** [comment]
Can u paste the content of heron-executor.stderr and heron-executor.stdout in:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/

The issues should be logged there.

**Comment by aaronshan** [comment]
@maosongfu 
I upload the log:
[log-files.tar.gz](https://github.com/twitter/heron/files/294705/log-files.tar.gz)
[heron-executor.stderr.tar.gz](https://github.com/twitter/heron/files/294708/heron-executor.stderr.tar.gz)
[heron-executor.stdout.tar.gz](https://github.com/twitter/heron/files/294709/heron-executor.stdout.tar.gz)

**Comment by maosongfu** [comment]
@aaronshan 
Checked the heron-executor.stdout, and found:

heron-tmaster exited with status 256
stmgr-1 exited with status 256

So pretty sure the issue is caused by lacking dependencies to start C++ program;  but it is wired that log-info is missing in heron-executor.stderr, so currently no way to know what those dependencies are.

You can diagnose by run the stream mgr's cmd directly in terminal, check the output and figure out the lacking dependencies.

We are working in progress to relief your issues too:
1. #505 
2. #853

**Comment by kramasamy** [comment]
If you want to compile for centos 6, you need to compile bazel. Bazel binaries do not work for centos6. Otherwise rest of the code should compile without any issues. We have tried in centos5 and it works.

**Comment by aaronshan** [comment]
@maosongfu Where can I find the stream mgr's cmd?

**Comment by maosongfu** [comment]
@aaronshan 
```
./heron-core/bin/heron-stmgr ExclamationTopology ExclamationTopology890e8b1c-ca60-485a-b00c-0a7c24350287 ExclamationTopology.defn LOCALMODE /home/q/heron/heron-0.14.0/herondata/repository/state/local stmgr-1 container_1_word_2,container_1_exclaim1_1 52697 40818 49201 ./heron-conf/heron_internals.yaml
```

**Comment by aaronshan** [comment]
@maosongfu thanks. I have resolved this problem. For centos6, It need to upgrade gcc and glibc verion. Except this, it need to install libunwind.
If cannot find libunwind, It will report error like this:
```
libunwind.so.8: cannot open shared object file: No such file or directory
```
If use default gcc and glibc, It will report error like this:
```
./heron-core/bin/heron-stmgr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./heron-core/bin/heron-stmgr)

./heron-core/bin/heron-stmgr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./heron-core/bin/heron-stmgr)

./heron-core/bin/heron-stmgr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./heron-core/bin/heron-stmgr)

./heron-core/bin/heron-stmgr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./heron-core/bin/heron-stmgr)

./heron-core/bin/heron-stmgr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./heron-core/bin/heron-stmgr)

./heron-core/bin/heron-stmgr: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./heron-core/bin/heron-stmgr)

```
After resolve above all problems, Heron will work in centos6(**use install-file that complied on centos7**).

**Comment by maosongfu** [comment]
#853 is fixed. Now people can figure out reasons failed to start process from:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout

**Comment by maosongfu** [comment]
Resolved
