### ISSUE TITLE
execute bazel build --config=darwin heron/... error

### ISSUE THREAD

**Issue by Jonathan-Wei** [twitter/heron#851]
Hi guys!
I execute bazel build --config=darwin heron/... command error
INFO: From Building heron/spi/tests/java/network-utils_unittest.jar (1 files):
heron/spi/tests/java/com/twitter/heron/spi/common/NetworkUtilsTest.java:41: 错误: 无法访问AbstractCommonPowerMockRunner
@RunWith(PowerMockRunner.class)
                        ^
  找不到org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner的类文件
heron/spi/tests/java/com/twitter/heron/spi/common/NetworkUtilsTest.java:216: 错误: 无法访问MemberModifier
    PowerMockito.spy(NetworkUtils.class);
                ^
  找不到org.powermock.api.support.membermodification.MemberModifier的类文件
2 个错误
BazelJavaBuilder threw exception: java compilation returned status ERROR
ERROR: /Users/jonathanwei/summary/GITRepository/heron/heron/spi/tests/java/BUILD:47:1: Java compilation in rule '//heron/spi/tests/java:network-utils_unittest' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by Jonathan-Wei** [comment]
Execute bazel build --config=darwin heron/... --verbose_failures command :

INFO: From Building heron/spi/tests/java/network-utils_unittest.jar (1 files):
heron/spi/tests/java/com/twitter/heron/spi/common/NetworkUtilsTest.java:41: 错误: 无法访问AbstractCommonPowerMockRunner
@RunWith(PowerMockRunner.class)
                        ^
  找不到org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner的类文件
heron/spi/tests/java/com/twitter/heron/spi/common/NetworkUtilsTest.java:216: 错误: 无法访问MemberModifier
    PowerMockito.spy(NetworkUtils.class);
                ^
  找不到org.powermock.api.support.membermodification.MemberModifier的类文件
2 个错误
BazelJavaBuilder threw exception: java compilation returned status ERROR
ERROR: /Users/jonathanwei/summary/GITRepository/heron/heron/spi/tests/java/BUILD:47:1: Java compilation in rule '//heron/spi/tests/java:network-utils_unittest' failed: java failed: error executing command
  (cd /private/var/tmp/_bazel_jonathanwei/f0e0d1fb1f89f02c31d3facf1d735668/heron && \
  exec env - \
  external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/local_darwin-fastbuild/bin/heron/spi/tests/java/network-utils_unittest.jar-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: java failed: error executing command
  (cd /private/var/tmp/_bazel_jonathanwei/f0e0d1fb1f89f02c31d3facf1d735668/heron && \
  exec env - \
  external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/local_darwin-fastbuild/bin/heron/spi/tests/java/network-utils_unittest.jar-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
INFO: Elapsed time: 4.737s, Critical Path: 4.08s.

**Comment by nlu90** [comment]
@Jonathan-Wei the powermock java library is missing.

Can you check the dir `bazel-bin/3rdparty/java` and see if any powermock jars in it? Like the following

```shell
[tw-mbp-nlu java]$ ls | grep powermock
libpowermock-ijar.jar
libpowermock.jar
libpowermock.jar-2.params
libpowermock.jar_manifest_proto
libpowermock.jdeps
```

**Comment by zhangzhonglai** [comment]
@Jonathan-Wei 
I got the same problem.
Following change can fix this issue.
```
diff --git a/3rdparty/java/BUILD b/3rdparty/java/BUILD
index a3a3688..e3250f4 100644
--- a/3rdparty/java/BUILD
+++ b/3rdparty/java/BUILD
@@ -99,8 +99,10 @@ java_library(
     srcs = [ "Empty.java" ],
     exports = [
         "@powermock-api-mockito//jar",
+       "@powermock-api-support//jar",
         "@powermock-core//jar",
         "@powermock-module-junit4//jar",
+       "@powermock-module-junit4-common//jar",
     ],
     deps = [
         "@powermock-api-mockito//jar",
```

**Comment by billonahill** [comment]
Great find @zhangzhonglai. Would you mind submitting a patch?

**Comment by zhangzhonglai** [comment]
@billonahill 
Yes. I'll try to do this.But I've never done this before. If there is something wrong, please tell me.

**Comment by Jonathan-Wei** [comment]
3Q!@zhangzhonglai @billonahill 
Build success!

**Comment by billonahill** [comment]
Great, glad it's working @Jonathan-Wei. Thanks for the patch @zhangzhonglai.
