### ISSUE TITLE
usage of undefined variable in heron/ui/src/python/handler/api/topology.py

### ISSUE THREAD

**Issue by alanngai** [twitter/heron#855]
when running linter on heron ui via 

bazel build --config=darwin --experimental_action_listener=tools/python:compile_python heron/ui/src/python/...

the following errors/warnings are reported for heron/ui/src/python/handler/api/topology.py.  

************* Module topology
W:231, 0: FIXME: is there a purpose to saving the return value of this? (fixme)
W:234, 0: FIXME: estate not defined (fixme)
E:240,15: Undefined variable 'estate' (undefined-variable)
W:232, 4: Unused variable 'scheduler_location' (unused-variable)

at the minimum, the undefined variable 'estate' should probably be fixed.

**Comment by objmagic** [comment]
Close this since we already fixed all the Python style errors after Pylint PR (#849 )
