### ISSUE TITLE
Move heron design goals to a separate page

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#860]

**Comment by osgigeek** [comment]
Suggest adding it at the same level as "Heron Architecture" under "Heron Concepts" and maybe naming the page "Heron Design Principles". Consider adding 

* Observability
* Failover - explaining no single point of failure
* Recoverability - recovery of state of bolts

**Comment by lucperkins** [comment]
I'm happy to write this up. @kramasamy, get in touch with me and let me know what information you'd like to see included.

**Comment by kramasamy** [comment]
@lucperkins - you can start with the design goals in the Heron Architecture section for Heron Design Goals.

**Comment by kramasamy** [comment]
@lucperkins - Any update on this?
