### ISSUE TITLE
how set  TOPOLOGY_WORKERS?

### ISSUE THREAD

**Issue by daxwang** [twitter/heron#864]
hi, guys:
in storm it can set topology workers with  conf.setNumWorkers(workersCount), how to set TOPOLOGY_WORKERS in heron api?

**Comment by supunkamburugamuve** [comment]
The concept of workers is absent in heron. In storm a worker can host multiple tasks and each task is executed as a separate process. AFAIK You can set the number of stream managers. This will determine number of containers you run. In these containers you'll spawn the individual processes.

**Comment by maosongfu** [comment]
You can use  conf.setNumWorkers(workersCount) in storm-compatible api, which is translated into number of containers/stream mgrs in heron when converting as a heron job.

**Comment by kramasamy** [comment]
Closing this since it has been answered.
