### ISSUE TITLE
how to kown  whether topology sumbit sucess or not?

### ISSUE THREAD

**Issue by daxwang** [twitter/heron#867]
hi,guys:
i submit topology by HeronSubmitter.submitTopology(topologyName, conf, topology)  in heron, but this function has no return code, how to kown  whether topology sumbit sucess or not ? is there any heron api?

**Comment by maosongfu** [comment]
There are output on the terminal indicating whether a topology was submitted successfully nor not.
Furthermore:
1. You can check the working directory (printed at the end of output)
2. Use heron-tracker or heron-ui, as getting started.

Another trick can be using "ps" command, though not reliable.
