### ISSUE TITLE
Error: Argument cluster/[role]/[env] is not correct 

### ISSUE THREAD

**Issue by kartik894** [twitter/heron#888]
Hi,

I got this error upon executing heron submit on aurora.
```
$ heron submit aurora --config-path ~/.heron/conf/ ~/.heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology
ERROR: Argument cluster/[role]/[env] is not correct: role required but not provided
```

**Comment by billonahill** [comment]
Looks like you're swapped the ordering of `[options]` and `cluster/[role]/[environ]`:
```
$ heron help submit
usage: heron submit [options] cluster/[role]/[environ] topology-file-name topology-class-name [topology-args]

Required arguments:
  cluster/[role]/[env]  Cluster, role, and environ to run topology
  topology-file-name    Topology jar/tar/zip file
  topology-class-name   Topology class name

Optional arguments:
  --config-path (a string; path to cluster config; default: "/Users/billg/.heron/conf/<cluster>")
  --config-property (a string; a config property; default: [])
  --deploy-deactivated (a boolean; default: "false")
  --verbose (a boolean; default: "false")
```

If that's not the cause, this is the relevant code to troubleshoot FYI:
https://github.com/twitter/heron/blob/master/heron/cli/src/python/main.py#L155

**Comment by kartik894** [comment]
Still getting the same error after swapping the command line arguments.

**Comment by billonahill** [comment]
What do you see when you add `--verbose` or debugging statements to the cli?

**Comment by kartik894** [comment]
Even after adding --verbose, getting the same output. 
ERROR: Argument cluster/[role]/[env] is not correct: role required but not provided

**Comment by billonahill** [comment]
Try adding some debug lines to the client code to see if this is a bug or an area where we need to improve output logging.

**Comment by nlu90** [comment]
@kartik894 can you check the client.yaml in your aurora conf dir? You should  see the following 2 confs:

```yaml
# Whether role/env is required to submit a topology. Default value is False.
heron.config.is.role.required:               True
heron.config.is.env.required:                True
```

Change the value to False if your aurora cluster doesn't require the `role` and `env` to be provided. Otherwise, you need to provide those two arguments when submitting the topology like follows:

```
heron submit aurora/{YOUR_ROLE}/{YOUR_ENV} --config-path ~/.heron/conf/ ~/.heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology
```

**Comment by billonahill** [comment]
If this does the trick, adding a reference to `client.yaml` in the cli output would be a great patch to help clarify this for future users.

**Comment by kartik894** [comment]
Thanks @nlu90 . Its working now

**Comment by billonahill** [comment]
@kartik894, @nlu90 see #894 for enhanced error logging patch.
