### ISSUE TITLE
Set correct file timestamp

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#910]
Referenced: #845 
----------------------

Uncompressing..tar: ./release.yaml: implausibly old time stamp 1970-01-01 08:00:00
tar: ./bin/heron: implausibly old time stamp 1970-01-01 08:00:00
tar: ./bin: implausibly old time stamp 1970-01-01 08:00:00
tar: ./conf/local/client.yaml: implausibly old time stamp 1970-01-01 08:00:00
tar: ./conf/local/heron_internals.yaml: implausibly old time stamp 1970-01-01 08:00:00
tar: ./conf/local/metrics_sinks.yaml: implausibly old time stamp 1970-01-01 08:00:00
tar: ./conf/local/packing.yaml: implausibly old time stamp 1970-01-01 08:00:00

Though it is a WARNING, it is good if we can remove it.

**Comment by maosongfu** [comment]
Travis-ci building also shows this WARNING during untar:
```
[2016-06-14 02:05:18 +0000] com.twitter.heron.spi.common.ShellUtils FINE:  $> [tar, -xvf, /home/travis/.herondata/topologies/local/heron-staging/1465869225_IntegrationTest_OneBoltMultiTasks_de8c043e-7d22-4ac4-ba17-902fbba5db81/topology.tar.gz]  
integration-tests.jar
1465869225_IntegrationTest_OneBoltMultiTasks_de8c043e-7d22-4ac4-ba17-902fbba5db81.defn
./heron-conf/
./heron-conf/heron_internals.yaml
tar: ./heron-conf/heron_internals.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/packing.yaml
tar: ./heron-conf/packing.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/uploader.yaml
tar: ./heron-conf/uploader.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/client.yaml
tar: ./heron-conf/client.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/scheduler.yaml
tar: ./heron-conf/scheduler.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/statemgr.yaml
tar: ./heron-conf/statemgr.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/metrics_sinks.yaml
tar: ./heron-conf/metrics_sinks.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/release.yaml
tar: ./heron-conf/release.yaml: implausibly old time stamp 1970-01-01 00:00:00
./heron-conf/override.yaml
tar: ./heron-conf: implausibly old time stamp 1970-01-01 00:00:00
```

**Comment by billonahill** [comment]
This is a bazel issue. All timestamps get reset upon build. Need to investigate more to see if we can change this.
https://github.com/bazelbuild/bazel/issues/1299
https://groups.google.com/forum/#!topic/bazel-discuss/cprd0UhRMAs

**Comment by billonahill** [comment]
These are warnings that can be ignored. Untarring with `--warning=no-timestamp` should suppress the warning. See https://www.gnu.org/software/tar/manual/html_node/warnings.html

**Comment by kramasamy** [comment]
@billonahill - awesome. Can we fix the scripts where we untar? They are the installer scripts.

**Comment by billonahill** [comment]
Ideally we'd fix the timestamps but that looks tricky due to bazel magic. Instead we suppressed the warnings for now. Will close this, but we can revisit to see if it's still an issue after upgrading to the latest bazel.
