### ISSUE TITLE
How can I config Topology Master Standby?

### ISSUE THREAD

**Issue by aaronshan** [twitter/heron#930]
As the title, from the paper [Twitter Heron: Stream Processing at Scale](http://dl.acm.org/citation.cfm?id=2742788), I learned that TM can configured to master-standby model .
![image](https://cloud.githubusercontent.com/assets/5170947/16112557/687f2a4c-33ea-11e6-911f-7dc35299f0f8.png)
But I can't find config method from heron document.
How can I config Topology Master Standby? Thanks.

**Comment by billonahill** [comment]
Not an issue, closing. Please discuss in the heron-users forum.
https://groups.google.com/forum/#!forum/heron-users
