### ISSUE TITLE
build failed with --  Process exited with status 1

### ISSUE THREAD

**Issue by vivilife** [twitter/heron#931]
On Centos7, run build command -- "bazel build --config=centos heron/... " failed, the output message is

[root@2893148ace85 heron-0.14.0]# ~/.bazel/bin/bazel build --config=centos heron/...
INFO: Found 321 targets...
ERROR: Process exited with status 1.
INFO: Elapsed time: 1.363s, Critical Path: 0.85s.

There is no detail about which caused the building fail, so how to fix this issue? Thanks

The configuration is as follow:
Platform Linux
Using C compiler          :	/usr/bin/gcc (4.8.5)
Using C++ compiler        :	/usr/bin/g++ (4.8.5)
Using C preprocessor      :	/usr/bin/cpp (4.8.5)
Using C++ preprocessor    :	/usr/bin/cpp (4.8.5)
Using linker              :	/usr/bin/ld.bfd
Using Automake            :	/usr/bin/automake (1.13.4)
Using Autoconf            :	/usr/bin/autoconf (2.69)
Using Make                :	/usr/bin/make (3.82)
Using CMake               :	/usr/bin/cmake (2.8.11)
Using Python2             :	/usr/bin/python2.7 (2.7.5)

**Comment by kramasamy** [comment]
@vivilife - Just wondering if you have installed libunwind. We have a docker file for centos7 under the docker/ directory. Please check what are the dependencies that you need to install before compiling in centos7.

**Comment by supunkamburugamuve** [comment]
@vivilife are you running the build as root? If that is the case, it will be worth running it under a normal user and see.

**Comment by vivilife** [comment]
I build the docker image using docker/Dockerfile.centos7 without the last line. Then I run the container, the same problem still exist. But after I copy the configuration params for centos from tools/bazel.rc to ~/.bazelrc and build with command " bazel build  heron/... ", build succedd.

I think there is some problem with my bazel,  so I bypass it with some trick
