### ISSUE TITLE
Add a new packing algorithm based on binpacking

### ISSUE THREAD

**Issue by avflor** [twitter/heron#934]

**Comment by ajorgensen** [comment]
To add an anecdote to this currently we are using a memory aware packing algorithm because we've found that we can get container sizes down by a pretty significant amount by taking memory into account. There are of course trade-offs here depending on the cpu requirements of each of the components but in general for topologies that have a few large components we've found that by sorting the components by memory required first and then using a round robin approach to place them in containers can reduce the total memory overhead where the number of containers is greater than or equal to the number of the instances of the largest component.

As an example if we have a topology that has the following characteristics:
Spot1: 2 x 500Mb RAM 
Bolt1: 2 x 500Mb RAM
Bolt2 4 x 2Gb RAM
with 3 containers a simple round robin might get you:
[S1_1, B1_2, B2_3] [S1_2, B2_1,B2_4] [B1_1, B2_2]

The largest container in this case would be the second one (1 Spot and 2 Bolt2s) with adds up to 4.5Gb of RAM needed. In the case of Aurora all of the containers need to be the same so we require 4.5Gb * 3 = 13.5 Gb of RAM total. If we take memory into account and increase the number of containers by one we can get away with
[B2_1, S1_1][B2_2, S1_2][B2_3, B1_1][B2_4, B1_2]

Which in this case we only need 2.5Gb per container or 10Gb of RAM total for a savings of 3.5Gb. 

I'm curious your thoughts on bin packing and the dimensions that you'd most care to optimize for.

**Comment by billonahill** [comment]
This approach seems reasonable to me. I think it would be good to support multiple packing algorithms, each which could be run in a dry-run mode for inspection by topology developers. We should expand the output to show a standard report of the plan and what the resource usage would look like if deployed. Users could manually inspect what the physical plan would look like with any of the algorithms before deploying. Ultimately the best algorithm could even be dynamically detected by the system at deploy time.

**Comment by avflor** [comment]
Andrew, I think the enhanced round robin algorithm is a reasonable approach under the assumption that the containers have to be homogeneous, which is a constraint imposed by Aurora. BTW, I'm not able to find the code for the enhanced round robin algorithm. It seems to me that currently the getRoundRobinAllocation() method does not perform any sorting.

In this issue, we try to address the packing problem optimizing for the resources used (currently memory) using binpacking algorithms. However, the input of the algorithm would be slightly different from what is currently used. More specifically, we will ask for the maximum container size in terms of ram, cpu and disk and the maximum number of containers. The algorithm will decide how many containers to use. Apart from homogeneous containers, this version of the algorithm will also work with heterogeneous containers that can be handled by schedulers such as Yarn. In this way, we can further improve the resource utilization for such environments. Finally, the binpacking algorithm can be extended in the future to handle multiple dimensions (e.g., cpu and disk requirements per component) when these are supported by Heron.  Do you know if there is any plan to support different cpu configurations per component? I would think that this would be useful for users with cpu-bound topologies. In this case, we could use a multi-dimensional binpacking algorithm that would take both memory and cpu into account.

I think Bill's suggestion to implement multiple packing algorithms and observe the resource usage at the tuning phase is a very good idea since it is not clear to me how different algorithms behave for various topologies and user configurations.

**Comment by ajorgensen** [comment]
Correct sorry I should have clarified that I have a custom packing
algorithm that I will try to get back into mainline when I have time. The
current round robin is just a standard round robin with no consideration
for memory, CPU, etc.

On Thursday, June 16, 2016, avflor <notifications@github.com> wrote:

> Andrew, I think the enhanced round robin algorithm is a reasonable
> approach under the assumption that the containers have to be homogeneous,
> which is a constraint imposed by Aurora. BTW, I'm not able to find the code
> for the enhanced round robin algorithm. It seems to me that currently the
> getRoundRobinAllocation() method does not perform any sorting.
>
> In this issue, we try to address the packing problem optimizing for the
> resources used (currently memory) using binpacking algorithms. However, the
> input of the algorithm would be slightly different from what is currently
> used. More specifically, we will ask for the maximum container size in
> terms of ram, cpu and disk and the maximum number of containers. The
> algorithm will decide how many containers to use. Apart from homogeneous
> containers, this version of the algorithm will also work with heterogeneous
> containers that can be handled by schedulers such as Yarn. In this way, we
> can further improve the resource utilization for such environments.
> Finally, the binpacking algorithm can be extended in the future to handle
> multiple dimensions (e.g., cpu and disk requirements per component) when
> these are supported by Heron. Do you know if there is any plan to support
> different cpu configurations per component? I would think that this would
> be useful for users with cpu-bound topologies. In this case, we could use a
> multi-dimensional binpacking algorithm that would take both memory and cpu
> into account.
>
> I think Bill's suggestion to implement multiple packing algorithms and
> observe the resource usage at the tuning phase is a very good idea since it
> is not clear to me how different algorithms behave for various topologies
> and user configurations.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/twitter/heron/issues/934#issuecomment-226635726>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAfHU30bXOll49z1Z2kEr4DE96qCAqjJks5qMdJ2gaJpZM4I3vbz>
> .
>


-- 
----
Andrew Jorgensen
@ajorgensen

**Comment by ajorgensen** [comment]
Sorry I should have been more clear, I have a implementation of bin packing for memory but it's not on master. I will try to get into a state that can be put into a pr when I have some time. 

Controlling for CPU is a bit more difficult. For the JVM you can pretty easily set the min and max heap size which controls for memory but there is no mechanism that I know of to control for CPU in the same way. For meoss and Aurora we have cgroups which provide CPU usage isolation to control for noisy neighbors but I'm not aware of a mechanism that could be applied to a specific processes in containers although I wonder if cgroups could be used for this as well.

I like the idea of the packing algorithm being able to determine the optimal number of containers so it uses the fewest overall resources. I think ideally it'd be nice to not have the containers need to be homogenous which would cut back on waste even more, I believe you can get this when running and managing tasks on meoss but it's not possible on Aurora.

**Comment by kramasamy** [comment]
@ajorgensen - it will be nice if you could push this soon into main repo. @avflor is working alternate and interesting packing algorithms.
