### ISSUE TITLE
Provide heron-spi artifact in maven central

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#935]
There is documentation referencing the use of heron-spi for building custom schedulers, packing algorithms, etc (http://twitter.github.io/heron/docs/contributors/custom-scheduler/) however it is not provided in [maven central](http://mvnrepository.com/artifact/com.twitter.heron). We should add this artifact so that it is available for people to easily include as a dependency.

**Comment by lewiskan** [comment]
@kramasamy building standalone "heron-spi" with ```bazel build --config=darwin heron/spi/src/java:heron-spi```  generates "libheron-spi.jar" located in ```bazel-out/local_darwin-fastbuild/bin/heron/spi/src/java```  

Is "libheron-spi.jar" correct jar to publish, if so, do we rename to "heron-spi" to match documentation, or do we need a new BUILD genrule similar to "heron-api" 

```
genrule(
    name = "heron-api",
    srcs = [":api-unshaded_deploy.jar"],
    outs = ["heron-api.jar"],
    cmd  = "cp $< $@",
)
```

**Comment by lewiskan** [comment]
@ajorgensen I see the PR https://github.com/twitter/heron/pull/937/files with genrule added, great, I'll wait for the merge then complete Maven Central publish, thanks.

**Comment by ajorgensen** [comment]
I was thinking that we just make it look the same as heron-api and treat it the same way. Using the genrul in the PR i was able to generate the jar and upload it to a private artifactory instance and include it in a project.

**Comment by lewiskan** [comment]
cool, my thoughts exactly!  thanks for generating the PR, i'll wait for merge before uploading to Maven.

**Comment by ajorgensen** [comment]
Sounds great. Thanks!
