### ISSUE TITLE
Make PackingPlan builder pattern

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#946]
Make PackingPlan builder pattern, allowing people to construct PackingPlan easier and safer.

**Comment by billonahill** [comment]
I've also been thinking about this as a way to simplfy the packing algorithms. I'd like to reduce the number of Maps and Collections passed around in that code and replace with a builder, specifically the `Map<Integer, List<InstanceId>> resource` that is used, as well as some of our shared `PackingUtil` static helpers. I've looked at the code a bit and I think an impl like this would work to encapsulate building/modifying packing plans:
```
public class PackingPlanBuilder {
  PackingPlanBuidler()
  PackingPlanBuidler(PackingPlan existingPacking)

  // topology settings
  void setTopologyId(String topologyId);

  // set resource settings
  void setDefaultInstanceResource(Resource resource);
  void setRequestedComponentRam(String componentName, long ram);
  void setRequestedContainerRam(long ram);
  void setRequestedContainerRamPadding(long ram);

  // add or remove instances
  void addInstance(Integer containerId, InstanceId instance);
  void removeInstance(Integer containerId, InstanceId instance);
  void removeAnyInstance(String componentName);

  // build container plan sets by summing up instance resources
  // mostly impl from PackingUtils.buildContainerPlans
  PackingPlan build() throws InvalidPackingExcepton;
}
```

cc/ @avflor @ashvina who have also been thinking about this.

**Comment by ashvina** [comment]
@billonahill In my opinion we are mixing two different interfaces in the proposed builder. Methods in the `add or remove instance` section are specific to update (or may be submit) topology process. Where Methods in the `set resource settings` section are related to constraints specified by the user in connection with the packing algorithm. For e.g. current `RoundRobin` implementation will need number of containers as a resource setting, while `FFD` will not use it. So I think any resource setting (constraints) specific methods should not be part of this interface.

**Comment by billonahill** [comment]
@ashvina the current workflow for both packing algorithms is that based on number of containers, the algos basically call `addInstance` to bind `InstanceId`s to containers. Once that's complete the build process converts `InstanceId`s into `InstancePlan`s to make the `PackingPlan`. This stage requires the notion of instance and container resources and is currently handled in [PackingUtils.buildContainerPlans](https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/PackingUtils.java#L93). 

The only real difference between `InstanceId`s and `InstancePlan`s is that the latter has resources, so it's not clear to me how we can have a packing plan builder that takes `InstanceId`s without taking some notion of resources. How do you suggest we change the API?

**Comment by avflor** [comment]
@billonahill The number of containers is provided as input at the RR algo but the other two algos can change the number of containers. Moreover, the way they add and remove instances from containers is specific to each packing algo. The Requested componentram, disk and cpu methods apply to the RR algos. We have different parameters for the binpacking algos (e.g., TOPOLOGY_CONTAINER_MAX_CPU_HINT). We could make all the algos use the same parameters.

**Comment by avflor** [comment]
@ashvina @billonahill I think the logic for creating the new packing plan should be left to each individual algo. The builder should hold and modify the data structures needed to produce the packing plan but should not incorporate the logic of generating a new packing plan.

**Comment by billonahill** [comment]
I spoke with @avflor and @ashvina to clarify that the placement/removal logic will still be up to the algo, the builder just handles the add/remove calls as directed. Also the resource settings included are generic across packing algo, like default instance resources and resource per component. These are also set by the packing algo based on user settings or configs. They're required to generate a packing plan with resources from the InstanceIds.

One thing we did realize is that `RoundRobinPacking` handles plan creation differently than the others (as a result it can over-allocate) so that class might not be able to upgrade to use the packing builder. We might just deprecate that one if we're able to replace it with the `ResourceCompliantRRPacking` impl.
