### ISSUE TITLE
Documentation for REEF Scheduler

### ISSUE THREAD

**Issue by kramasamy** [twitter/heron#947]
Please include a page for documentation on how to use REEF. You can follow the same template similar to other schedulers.

**Comment by kramasamy** [comment]
@ashvina - I will be nice to add this documentation.

**Comment by ashvina** [comment]
@kramasamy I am working on the doc and planning to post the first draft by today evening.

**Comment by ashvina** [comment]
Sample doc page: http://ashvina.github.io/heron/docs/operators/deployment/schedulers/yarn/. I think the doc is missing commands and information about log directories. I am adding these details.
