### ISSUE TITLE
YARN scheduler must start TMaster and Heron Scheduler in the same container

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#951]
Currently Heron scheduler is co-located with topology AM and TMaster is started in its own container. It is better to keep Scheduler and TMaster in the same container. Which means a heron topology on YARN will have n+2 containers. 1 for AM, 1 for TMaster+Scheduler and N worker nodes.

**Comment by ashvina** [comment]
Hi @maosongfu. I am looking at `AuroraLauncher`. It uses `Scheduler` as a library [ref] (https://github.com/twitter/heron/blob/master/heron/schedulers/src/java/com/twitter/heron/scheduler/aurora/AuroraLauncher.java#L48). Which means scheduler is not needed by topology master or instances and hence there will be no issues if YARN scheduler keeps the TMaster in a different container.

**Comment by Laxman-SM** [comment]
HI kramasamy,
presently heron topology on AURORA will have n+3 containers. 1 for AM, 1 for TMasterand 1 for Scheduler and N worker nodes. this logic also applied for Aurora ?

**Comment by huijunwu** [comment]
@Laxman-SM N+1 for Aurora. There is no AM nor Scheduler containers. Only Tmaster container exists.
