### ISSUE TITLE
Flaky unit test case "//heron/schedulers/tests/java:HeronMasterDriverTest "

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#961]
It passed here: https://travis-ci.org/twitter/heron/builds/139093389
But it failed here: https://travis-ci.org/twitter/heron/builds/139093489

**Comment by ashvina** [comment]
@maosongfu I am looking at this. Do you know if the build logs are available somewhere?

**Comment by maosongfu** [comment]
@ashvina Currently travis-ci does not provide the feature to fetch data from the building container.
