### ISSUE TITLE
Heron UI does not properly display single instance topologies

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#976]
The heron UI required there to be at least one connection in order to draw the DAG. There are use cases where a topology might only have a single instance and we want to be able to draw it in that state as well.

Currently if you deploy a topology with a single instance the UI will look like:
![image](https://cloud.githubusercontent.com/assets/509779/16307959/34c274f6-3931-11e6-9933-27168e1dd415.png)

**Comment by kramasamy** [comment]
@objmagic - whenever you get some time, please take a look at this.
