### ISSUE TITLE
update dev documentation to install bazel 0.2.3

### ISSUE THREAD

**Issue by alanngai** [twitter/heron#978]
dev setup docs have instructions to setup bazel 0.1.2.  But master uses 0.2.3.

http://twitter.github.io/heron/docs/developers/compiling/compiling/
http://twitter.github.io/heron/docs/developers/compiling/compiling/

**Comment by kramasamy** [comment]
Fixed in #942 in PR - we need to launch the site.

**Comment by kramasamy** [comment]
@lucperkins - can we relaunch the doc site?

**Comment by kramasamy** [comment]
This is completed.
