### ISSUE TITLE
Hard coded repo name in links on pages

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#988]
The href attribute in index pages generated by `make site` starts with repo name as `heron` (for e.g. https://github.com/twitter/heron/blob/gh-pages/docs/operators/deployment/schedulers/aurora/index.html). In most cases a fork of `twitter/heron` will have heron as repo name. However the repo name can be updated. For example I can name my fork as `heron-streaming`. If the repo name is different, the links in the fork's site will not work. Is it feasible to use the repo name when page is generated?

To reproduce, create a fork and name it heron-streaming. Publish site and traverse the scheduler doc links.

**Comment by objmagic** [comment]
By "repo name", do you mean the name which is displayed here?

![image](https://cloud.githubusercontent.com/assets/3656079/16387973/ee13e29c-3c4b-11e6-9890-c3f8e7aab6b2.png)

If so, I don't think it is possible... 

(well, of course, you can use ``curl`` to get the source of forked GitHub project page and find the string "ashvina/heron-streaming", and then blah blah blah. However, this sounds absurd to me...)

**Comment by ashvina** [comment]
I am referring to hard coded value of `baseurl=/heron` in `https://github.com/twitter/heron/blob/master/website/config.yaml`. Here `heron` is the git repository name. A fork may have a different name. It is rare, not sure if I will call it absurd. 

For now I will close this issue.

**Comment by objmagic** [comment]
Thanks for pointing it out. I didn't mean this problem is absurd. I mean my half-joking solution is absurd.

I think changing forked repo name is a rare scenario, and it is not necessary to fix your issue.

**Comment by objmagic** [comment]
I believe this is a problem related to publishing GitHub page. The GitHub page has to be published under ``twitter.github.io/heron`` (team_url/project_name). This means ``baseurl`` has to be ``heron`` for us. If you have modified repo name on GitHub and want to publish your own webpage on GitHub page, you may need to modify ``baseurl`` field.
