### ISSUE TITLE
Link in Custom Metrics Sinks doc points to 404

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#994]
> Your implementation of those interfaces will need to be packaged into a JAR file and distributed to the metrics-mgr-classpath folder of your [Heron release](http://twitter.github.io/heron/docs/developers/compiling/).

Specifically `Heron release` points to http://twitter.github.io/heron/docs/developers/compiling/ which does not exist.

**Comment by billonahill** [comment]
@objmagic could you check why linkchecker didn't catch this?

**Comment by objmagic** [comment]
let me see..

**Comment by objmagic** [comment]
``curl http://localhost:1313/heron/docs/developers/compiling/`` returns the following with status code 200:

    <pre>
    </pre>

This means ``wget`` will think the link to this page is not broken. I am not sure why ``curl`` gives me the above result, while ``curl -I http://twitter.github.io/heron/docs/developers/compiling/`` gives me ``HTTP/1.1 404 Not Found``

---
cc @lucperkins,
would you like to comment on this issue?
